// AUTO-GENERATED by tools/rh/gen_player_graphics.py
#define RH_PLAYER_PACK_COUNT 13
extern const u16 gRhPlayerPal0[];
extern const u16 gRhPlayerPal1[];
extern const u16 gRhPlayerPal2[];
extern const u16 gRhPlayerPal3[];
extern const u16 gRhPlayerPal4[];
extern const u16 gRhPlayerPal5[];
extern const u16 gRhPlayerPal6[];
extern const u16 gRhPlayerPal7[];
extern const u16 gRhPlayerPal8[];
extern const u16 gRhPlayerPal9[];
extern const u16 gRhPlayerPal10[];
extern const u16 gRhPlayerPal11[];
extern const u16 gRhPlayerPal12[];
