#!/usr/bin/env python3
"""Per-generation base stats and move data for "Update Base Stats to Generation" / "Update Moves to Generation".
Compiles src/pokemon.c and src/move.c with the expansion's P_UPDATED_STATS / B_UPDATED_MOVE_DATA / B_UPDATED_MOVE_TYPES
set to each generation, reads gSpeciesInfo / gMovesInfo from the objects and writes only what differs from the
latest data to src/data/rh_gen_data.h."""
import os, subprocess, sys, re
from concurrent.futures import ThreadPoolExecutor
from elftools.elf.elffile import ELFFile
sys.path.insert(0, os.path.dirname(__file__))
R = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')) + '/'
VER = 'FIRERED'
TMP = R + 'build/rh_tmp/gens'
os.makedirs(TMP, exist_ok=True)

# struct layouts via the species extractor helper (compiles a -g object)
import importlib.util
spec_src = open(R + 'tools/rh/species_extract.py').read()
layout_part = spec_src.split("f = open(ELF, 'rb')")[0]
g = {'__file__': R + 'tools/rh/species_extract.py'}
sys_argv = sys.argv; sys.argv = [sys.argv[0], R + 'pokefirered.elf', VER]
exec(compile(layout_part, 'species_extract_layout', 'exec'), g)
sys.argv = sys_argv
SI, MV = g['SI'], g['MV']
def field(buf, m):
    kind, a, b = m
    if kind == 'bytes':
        return int.from_bytes(buf[a:a + b], 'little')
    v = int.from_bytes(buf, 'little'); return (v >> a) & ((1 << b) - 1)
SI_SIZE, MV_SIZE = g['SI_SIZE'], g['MV_SIZE']

CPPFLAGS = ['-iquote', R + 'include', '-Wno-trigraphs', '-DMODERN=1', '-DTESTING=0', f'-D{VER}', '-std=gnu17']
CFLAGS = ['-mthumb', '-mthumb-interwork', '-O1', '-mabi=apcs-gnu', '-mtune=arm7tdmi', '-march=armv4t',
          '-Wno-pointer-to-int-cast', '-std=gnu17', '-w']
CC1 = subprocess.check_output(['arm-none-eabi-gcc', '--print-prog-name=cc1']).decode().strip()

def compile_obj(src, defines, out):
    cmd = (f"cd {R} && arm-none-eabi-cpp {' '.join(CPPFLAGS)} {' '.join(defines)} {src} | tools/preproc/preproc -i -g build/assets {src} charmap.txt"
           f" | {CC1} -quiet {' '.join(CFLAGS)} -o - - | arm-none-eabi-as -mcpu=arm7tdmi -march=armv4t -meabi=5 --defsym MODERN=1 --defsym {VER}=1 -o {out} -")
    subprocess.check_call(cmd, shell=True, executable='/bin/bash')
    return out

def read_symbol(obj, name):
    with open(obj, 'rb') as f:
        e = ELFFile(f)
        st = e.get_section_by_name('.symtab')
        s = st.get_symbol_by_name(name)[0]
        sec = e.get_section(s['st_shndx'])
        return sec.data()[s['st_value']:s['st_value'] + s['st_size']]

GENS = list(range(1, 10))  # GEN_1..GEN_9 (9 = latest)
jobs = []
with ThreadPoolExecutor(max_workers=4) as ex:
    futs = {}
    for gn in GENS:
        gdef = f'GEN_{gn}'
        futs[('s', gn)] = ex.submit(compile_obj, 'src/pokemon.c', [f'-DP_UPDATED_STATS={gdef}'], f'{TMP}/pokemon_{gn}.o')
        futs[('m', gn)] = ex.submit(compile_obj, 'src/move.c', [f'-DB_UPDATED_MOVE_DATA={gdef}', f'-DB_UPDATED_MOVE_TYPES={gdef}'], f'{TMP}/move_{gn}.o')
    objs = {k: v.result() for k, v in futs.items()}

STATS = ['baseHP', 'baseAttack', 'baseDefense', 'baseSpeed', 'baseSpAttack', 'baseSpDefense']
def species_stats(obj):
    data = read_symbol(obj, 'gSpeciesInfo')
    n = len(data) // SI_SIZE
    return [tuple(field(data[i * SI_SIZE:(i + 1) * SI_SIZE], SI[k]) for k in STATS) for i in range(n)]

MFIELDS = ['power', 'accuracy', 'pp', 'type', 'category']
def move_data(obj):
    data = read_symbol(obj, 'gMovesInfo')
    n = len(data) // MV_SIZE
    return [tuple(field(data[i * MV_SIZE:(i + 1) * MV_SIZE], MV[k]) for k in MFIELDS) for i in range(n)]

latestS = species_stats(objs[('s', 9)])
latestM = move_data(objs[('m', 9)])
c = '// AUTO-GENERATED by tools/rh/gen_gen_data.py - do not edit by hand\n'
c += '// Base stats / move data of older generations, only where they differ from the current data.\n'
c += 'struct RhGenStats { u16 species; u8 stats[6]; };  // HP, Atk, Def, Speed, SpAtk, SpDef\n'
c += 'struct RhGenMove { u16 move; u8 power; u8 accuracy; u8 pp; u8 type; u8 category; u8 pad; };\n'
counts_s, counts_m = [], []
for gn in range(1, 9):
    st = species_stats(objs[('s', gn)])
    diffs = [(i, st[i]) for i in range(min(len(st), len(latestS))) if st[i] != latestS[i]]
    c += f'static const struct RhGenStats sRhGenStats{gn}[] = {{\n'
    for i, v in diffs:
        c += f'    {{{i}, {{{", ".join(map(str, v))}}}}},\n'
    c += '    {0xFFFF}\n};\n'
    counts_s.append(len(diffs))
    mv = move_data(objs[('m', gn)])
    diffs = [(i, mv[i]) for i in range(min(len(mv), len(latestM))) if mv[i] != latestM[i]]
    c += f'static const struct RhGenMove sRhGenMoves{gn}[] = {{\n'
    for i, v in diffs:
        c += f'    {{{i}, {", ".join(map(str, v))}, 0}},\n'
    c += '    {0xFFFF}\n};\n'
    counts_m.append(len(diffs))
c += 'static const struct RhGenStats *const sRhGenStats[] = { NULL, ' + ', '.join(f'sRhGenStats{gn}' for gn in range(1, 9)) + ', NULL };\n'
c += 'static const struct RhGenMove *const sRhGenMoves[] = { NULL, ' + ', '.join(f'sRhGenMoves{gn}' for gn in range(1, 9)) + ', NULL };\n'
open(R + 'src/data/rh_gen_data.h', 'w').write(c)
print('stat diffs per gen', counts_s)
print('move diffs per gen', counts_m)
