#!/usr/bin/env python3
"""FVX "Balance Shop Item Prices" table (Gen 7 list, which covers modern items) -> src/data/rh_prices.h"""
import re, os
R = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')) + '/'
FVX = '/home/claude/work/fvx/romio/src/main/java/com/uprfvx/romio/constants/'
items_h = open(R + 'include/constants/items.h').read()
valid = set(re.findall(r'\b(ITEM_\w+)\b', items_h))
def snake(n):
    s = re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', n)
    s = re.sub(r'([A-Z])([A-Z][a-z])', r'\1_\2', s)
    return 'ITEM_' + s.upper()
prices = {}
for f in ['Gen7Constants.java', 'Gen3Constants.java']:      # Gen 3 (this game) wins; Gen 7 adds modern items
    src = open(FVX + f).read()
    block = src[src.index('balancedItemPrices'):]
    block = block[:block.index('}).collect')]
    for name, price in re.findall(r'\{ItemIDs\.(\w+),\s*(\d+)\}', block):
        if f.startswith('Gen7') and re.match(r'(tm|hm)\d+$', name, re.I):
            continue                                         # Gen 7 TM numbers are different moves
        prices[snake(name)] = int(price)
ALIAS = {'ITEM_THUNDERSTONE': 'ITEM_THUNDER_STONE', 'ITEM_X_SPECIAL': 'ITEM_X_SP_ATK', 'ITEM_X_SP_DEF': 'ITEM_X_SP_DEF',
         'ITEM_PARLYZ_HEAL': 'ITEM_PARALYZE_HEAL', 'ITEM_ENERGYPOWDER': 'ITEM_ENERGY_POWDER', 'ITEM_TINYMUSHROOM': 'ITEM_TINY_MUSHROOM',
         'ITEM_BLACK_GLASSES': 'ITEM_BLACK_GLASSES', 'ITEM_NEVERMELTICE': 'ITEM_NEVER_MELT_ICE', 'ITEM_SILVERPOWDER': 'ITEM_SILVER_POWDER',
         'ITEM_TWISTEDSPOON': 'ITEM_TWISTED_SPOON', 'ITEM_BRIGHTPOWDER': 'ITEM_BRIGHT_POWDER', 'ITEM_DEEPSEATOOTH': 'ITEM_DEEP_SEA_TOOTH',
         'ITEM_DEEPSEASCALE': 'ITEM_DEEP_SEA_SCALE', 'ITEM_UPGRADE': 'ITEM_UP_GRADE', 'ITEM_KINGS_ROCK': 'ITEM_KINGS_ROCK'}
out, missing = {}, []
for k, v in prices.items():
    k2 = ALIAS.get(k, k)
    if k2 in valid:
        out[k2] = v
    else:
        missing.append(k)
h = '// AUTO-GENERATED by tools/rh/gen_prices.py - FVX balanced shop prices\n'
h += '// Indexed by item id; 0 = not in the table (keep the normal price).\n'
h += 'static const u16 sRhBalancedPrices[ITEMS_COUNT] = {\n'
for k in sorted(out):
    h += f'    [{k}] = {min(out[k], 65535)},\n'
h += '};\n'
open(R + 'src/data/rh_prices.h', 'w').write(h)
print(len(out), 'prices;', len(missing), 'unmatched:', ' '.join(missing[:60]))
