#!/usr/bin/env python3
"""Generates move/item/trainer/static tables for the in-game randomizer.
Output: src/data/rh_randomizer_tables.h"""
import json, os, re, sys, glob
R = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')) + '/'
VER = sys.argv[1] if len(sys.argv) > 1 else 'firered'
M = json.load(open(R + f'build/rh_moves_{VER}.json'))
S = json.load(open(R + f'build/rh_species_{VER}.json'))
MAP_SUFFIX = '_Frlg' if VER == 'firered' else ''
out = '// AUTO-GENERATED by tools/rh/gen_randomizer_tables.py - do not edit by hand\n\n'

# ---------------- moves ----------------
moves_h = open(R + 'include/constants/moves.h').read()
first_z = int(re.search(r'MOVE_\w+\s*=\s*(\d+),\s*\n\s*MOVES_COUNT_GEN9', moves_h).group(1)) + 1
BROKEN_EFFECTS = {'EFFECT_OHKO', 'EFFECT_FIXED_HP_DAMAGE', 'EFFECT_LEVEL_DAMAGE', 'EFFECT_FIXED_PERCENT_DAMAGE',
                  'EFFECT_SKETCH', 'EFFECT_TRANSFORM'}
TYPES = ['TYPE_NORMAL', 'TYPE_FIGHTING', 'TYPE_FLYING', 'TYPE_POISON', 'TYPE_GROUND', 'TYPE_ROCK', 'TYPE_BUG', 'TYPE_GHOST',
         'TYPE_STEEL', 'TYPE_FIRE', 'TYPE_WATER', 'TYPE_GRASS', 'TYPE_ELECTRIC', 'TYPE_PSYCHIC', 'TYPE_ICE', 'TYPE_DRAGON',
         'TYPE_DARK', 'TYPE_FAIRY']
pool = []
for name, d in M.items():
    i = d['id']
    if i == 0 or i >= first_z or d['metronomeBanned'] or d['type'] not in TYPES: continue
    dmg = d['category'] in (1, 2) and d['power'] > 1
    broken = d['effectName'] in BROKEN_EFFECTS
    pool.append((TYPES.index(d['type']), i, name, dmg, broken))
pool.sort()
out += 'struct RhMove { u16 move; u8 type; u8 damaging:1; u8 broken:1; u8 pad:6; };\n'
out += f'#define RH_MOVE_COUNT {len(pool)}\nstatic const struct RhMove sRhMoves[RH_MOVE_COUNT] = {{\n'
for t, i, n, dmg, br in pool: out += f'    {{{n}, {TYPES[t]}, {int(dmg)}, {int(br)}, 0}},\n'
out += '};\n'
starts = []
for t in range(len(TYPES) + 1):
    starts.append(next((k for k, p in enumerate(pool) if p[0] >= t), len(pool)))
out += 'static const u16 sRhMoveTypeStart[] = { ' + ', '.join(map(str, starts)) + ' }; // index by position in sRhTypes\n'
out += 'static const u8 sRhTypes[] = { ' + ', '.join(TYPES) + ' };\n\n'

# ---------------- items ----------------
items_src = open(R + 'src/data/items.h').read()
sections, cur = {}, None
for line in items_src.split('\n'):
    m = re.match(r'^// (.+)$', line)
    if m: cur = m.group(1); continue
    m = re.match(r'^    \[ITEM_(\w+)\]', line)
    if m: sections.setdefault(cur, []).append(m.group(1))
GOOD_SECTIONS = ['Poké Balls', 'Medicine', 'Vitamins', 'EV Feathers', 'Mints', 'Candies', 'Encounter Modifiers', 'X items',
                 'Treasures', 'Evolution items', 'Gems', 'Incenses', 'Power items', 'Type-enhancing items', 'Choice items',
                 'Status Orbs', 'Weather Rocks', 'Terrain Seeds', 'Type-activated stat modifiers', 'Miscellaneous Held items',
                 'Berries', 'Species-specific Stat-enhancing items', 'Ability Modifiers', 'Mega Stones', 'Z-Crystals', 'Plates',
                 'Memories', 'Drives', 'Local specialties', 'Medicinal Flutes', 'Encounter-modifying Flutes', 'Nectars']
BAD_ITEMS = {'STRANGE_BALL', 'MASTER_BALL', 'CHERISH_BALL', 'PARK_BALL', 'SAFARI_BALL', 'DREAM_BALL', 'BEAST_BALL', 'SPORT_BALL',
             'DYNAMAX_CANDY', 'ENIGMA_BERRY_E_READER', 'SOUL_DEW', 'RUSTED_SWORD', 'RUSTED_SHIELD', 'EXP_SHARE',
             'RELIC_COPPER', 'RELIC_SILVER', 'RELIC_VASE', 'RELIC_BAND', 'RELIC_STATUE', 'RELIC_CROWN', 'SHOAL_SALT', 'SHOAL_SHELL',
             'ODD_KEYSTONE', 'STRANGE_SOUVENIR', 'RED_SHARD', 'BLUE_SHARD', 'YELLOW_SHARD', 'GREEN_SHARD', 'HEART_SCALE'}
JUNK = {'TINY_MUSHROOM', 'PRETTY_FEATHER', 'HONEY', 'BLACK_FLUTE', 'WHITE_FLUTE', 'BLUE_FLUTE', 'YELLOW_FLUTE', 'RED_FLUTE',
        'FRESH_WATER', 'SODA_POP', 'BERRY_JUICE', 'LAGGING_TAIL', 'IRON_BALL', 'RING_TARGET', 'STICKY_BARB', 'FULL_INCENSE',
        'BLACK_SLUDGE', 'CLEANSE_TAG', 'SMOKE_BALL', 'SOOTHE_BELL', 'POKE_DOLL', 'FLUFFY_TAIL', 'POKE_TOY'}
item_pool = []
for sec in GOOD_SECTIONS:
    for it in sections.get(sec, []):
        if it in BAD_ITEMS: continue
        item_pool.append((it, int(it in JUNK)))
out += 'struct RhItem { u16 item; u8 junk; };\n'
out += f'#define RH_ITEM_COUNT {len(item_pool)}\nstatic const struct RhItem sRhItems[RH_ITEM_COUNT] = {{\n'
for it, j in item_pool: out += f'    {{ITEM_{it}, {j}}},\n'
out += '};\n\n'

# ---------------- field items (item balls + hidden) ----------------
ball_items = dict(re.findall(r'^(\w+)::\n\tfinditem (ITEM_\w+)', open(R + 'data/scripts/item_ball_scripts_frlg.inc' if VER == 'firered' else R + 'data/scripts/item_ball_scripts.inc').read(), re.M))
field = []
for mj in sorted(glob.glob(R + f'data/maps/*{MAP_SUFFIX}/map.json')):
    m = json.load(open(mj))
    for o in m.get('object_events', []):
        sc = o.get('script')
        if sc in ball_items and o.get('flag', '0') not in ('0', ''):
            field.append((o['flag'], ball_items[sc]))
    for b in m.get('bg_events', []):
        if b.get('type') == 'hidden_item':
            field.append((b['flag'], b['item']))
field = sorted(set(field))
out += '// Every item ball / hidden item in the game, keyed by its flag (for "shuffle" mode).\n'
out += 'struct RhFieldItem { u16 flag; u16 item; };\n'
out += f'#define RH_FIELD_ITEM_COUNT {len(field)}\nstatic const struct RhFieldItem sRhFieldItems[RH_FIELD_ITEM_COUNT] = {{\n'
for f, it in field: out += f'    {{{f}, {it}}},\n'
out += '};\n\n'

# ---------------- gym / elite four type themes ----------------
GYMS = {'PewterCity_Gym': 'TYPE_ROCK', 'CeruleanCity_Gym': 'TYPE_WATER', 'VermilionCity_Gym': 'TYPE_ELECTRIC',
        'CeladonCity_Gym': 'TYPE_GRASS', 'FuchsiaCity_Gym': 'TYPE_POISON', 'SaffronCity_Gym': 'TYPE_PSYCHIC',
        'CinnabarIsland_Gym': 'TYPE_FIRE', 'ViridianCity_Gym': 'TYPE_GROUND',
        'PokemonLeague_LoreleisRoom': 'TYPE_ICE', 'PokemonLeague_BrunosRoom': 'TYPE_FIGHTING',
        'PokemonLeague_AgathasRoom': 'TYPE_GHOST', 'PokemonLeague_LancesRoom': 'TYPE_DRAGON'}
themes = []
for mp, t in GYMS.items():
    p = R + f'data/maps/{mp}{MAP_SUFFIX}/scripts.inc'
    for tr in sorted(set(re.findall(r'trainerbattle\w*\s+(TRAINER_\w+)', open(p).read()))):
        themes.append((tr, t))
out += 'struct RhTrainerTheme { u16 trainer; u8 type; };\n'
out += 'static const struct RhTrainerTheme sRhTrainerThemes[] = {\n'
for tr, t in themes: out += f'    {{{tr}, {t}}},\n'
out += '};\n\n'

# ---------------- static / gift Pokemon ----------------
statics = set()
for sc in glob.glob(R + f'data/maps/*{MAP_SUFFIX}/scripts.inc'):
    if 'ProfessorOaksLab' in sc: continue
    txt = open(sc).read()
    for m in re.finditer(r'^\s*(?:givemon|setwildbattle|giveegg)\s+(SPECIES_\w+)', txt, re.M):
        statics.add(m.group(1))
    for m in re.finditer(r'^\s*setvar\s+VAR_\w+,\s*(SPECIES_\w+)', txt, re.M):
        statics.add(m.group(1))
for sc in glob.glob(R + 'data/scripts/*.inc'):
    txt = open(sc).read()
    for m in re.finditer(r'^\s*(?:givemon|setwildbattle|giveegg)\s+(SPECIES_\w+)', txt, re.M):
        statics.add(m.group(1))
ALIAS = dict(re.findall(r'^\s*(SPECIES_\w+)\s*=\s*(SPECIES_\w+)\s*,', open(R + 'include/constants/species.h').read(), re.M))
def canon(n):
    for _ in range(4):
        if n in S: return n
        n = ALIAS.get(n, n)
    return n
STARTERS = {'SPECIES_BULBASAUR', 'SPECIES_CHARMANDER', 'SPECIES_SQUIRTLE', 'SPECIES_TREECKO', 'SPECIES_TORCHIC', 'SPECIES_MUDKIP'}
statics = sorted({canon(s) for s in statics if s not in STARTERS and canon(s) in S and S[canon(s)]['natDexNum'] and s not in ('SPECIES_NONE', 'SPECIES_EGG')},
                 key=lambda n: S[n]['id'])
out += '// Species given/fought through scripts (gifts, static encounters, game corner prizes...).\n'
out += 'static const u16 sRhStaticSpecies[] = {\n'
for s in statics: out += f'    {s},\n'
out += '};\n'
open(R + 'src/data/rh_randomizer_tables.h', 'w').write(out)
print('moves', len(pool), 'items', len(item_pool), 'field items', len(field), 'trainer themes', len(themes), 'statics', len(statics))
print('statics:', [s[8:] for s in statics])
