#!/usr/bin/env python3
"""Builds randomizer lookup tables from extracted species data.
Output: src/data/rh_randomizer_data.h"""
import json, os, sys
sys.path.insert(0, os.path.dirname(__file__))
R = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')) + '/'
VER = sys.argv[1] if len(sys.argv) > 1 else 'firered'
S = json.load(open(R + f'build/rh_species_{VER}.json'))
import gen_safari as G  # reuse FORM_GROUPS / helpers (it regenerates safari data too, harmless)

GEN_RANGES = G.GEN_RANGES
def gen_of(d): return G.gen_of(d)
BAD = G.BAD_FLAGS
prevo = G.prevo
def stage(sp): return G.stage(sp)
def legendary(v): return G.legendary(v)
def is_regional(v): return G.is_regional(v)

def children(sp):
    return [e['target'] for e in S[sp]['evolutions'] if e['target'] in S and e['target'] != sp]
def chain_len(sp, d=0):
    ch = children(sp)
    if not ch or d > 4: return 1
    return 1 + max(chain_len(c, d + 1) for c in ch)

def form_base(sp):
    v = S[sp]; return v['forms'][0] if v['forms'] else sp
def family_root(sp):
    b = form_base(sp)
    if is_regional(S[sp]): b = sp  # regional forms have their own family (evolve into regional evos)
    seen = 0
    while b in prevo and seen < 5:
        b = prevo[b]; seen += 1
    return b

wild_variant_forms = set()
for sp, fg in G.GROUPS_CANON.items():
    members = [f for f in S[sp]['forms'] if f in S and not any(S[f].get(x) for x in BAD) and not is_regional(S[f])] if fg == 'all' else [G.canon('SPECIES_' + f) for f in fg]
    for m in members:
        if m != sp: wild_variant_forms.add(m)

pool = []
for sp, v in sorted(S.items(), key=lambda kv: kv[1]['id']):
    dex = v['natDexNum']
    if not (1 <= dex <= 1025) or sp in ('SPECIES_NONE', 'SPECIES_EGG'): continue
    if any(v.get(f) for f in BAD) or any(p in sp for p in G.BAD_NAME_PARTS): continue
    reg = is_regional(v)
    base = form_base(sp) == sp
    variant = reg or sp in wild_variant_forms
    if not base and not variant: continue
    bst = sum(v[k] for k in ['baseHP', 'baseAttack', 'baseDefense', 'baseSpeed', 'baseSpAttack', 'baseSpDefense'])
    g = gen_of(dex)
    st = stage(sp); cl = chain_len(sp)
    pool.append(dict(sp=sp, gen=g, leg=int(bool(legendary(v))), variant=int(variant), stage=st, chain=min(3, st + cl - 1), bst=bst, dex=dex))

c = '// AUTO-GENERATED by tools/rh/gen_randomizer_data.py - do not edit by hand\n'
c += '// gen: generation of the species (1-9). variant: regional or cosmetic form (only in the "all + forms" pool).\n'
c += '// stage: evolution stage (1 = basic). chain: total stages in its line. bst: vanilla base stat total.\n'
c += 'struct RhPoolMon { u16 species; u16 bst; u8 gen:4; u8 stage:2; u8 legendary:1; u8 variant:1; u8 chain:2; u8 pad:6; };\n'
c += f'#define RH_POOL_COUNT {len(pool)}\n'
c += 'static const struct RhPoolMon sRhPool[RH_POOL_COUNT] = {\n'
for p in pool:
    c += f"    {{{p['sp']}, {p['bst']}, {p['gen']}, {p['stage']}, {p['leg']}, {p['variant']}, {p['chain']}, 0}},\n"
c += '};\n\n'
# family root for every species id (for "follow evolutions" options)
ids = sorted(S.values(), key=lambda v: v['id'])
maxid = max(v['id'] for v in ids)
byid = {v['id']: k for k, v in S.items()}
c += 'static const u16 sRhFamilyRoot[] = {\n'
for i in range(maxid + 1):
    sp = byid.get(i)
    c += f'    [{sp}] = {family_root(sp)},\n' if sp and sp not in ('SPECIES_NONE', 'SPECIES_EGG') else ''
c += '};\n'
open(R + 'src/data/rh_randomizer_data.h', 'w').write(c)
from collections import Counter
print('pool', len(pool), 'variants', sum(p['variant'] for p in pool), 'legendary', sum(p['leg'] for p in pool),
      'by gen', sorted(Counter(p['gen'] for p in pool).items()), '3-stage basics', sum(1 for p in pool if p['stage'] == 1 and p['chain'] == 3))
