#!/usr/bin/env python3
"""FVX's evolution level estimate (AbstractRomHandler.findEvolutionLevel) as a lookup table.
Samples: every vanilla level-up evolution (pre BST, post BST, level). The table holds the estimate for
(pre BST, post BST) on a 10-BST grid, so the GBA only needs a lookup. Output: src/data/rh_evo_levels.h"""
import json, math, os, sys
R = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')) + '/'
VER = sys.argv[1] if len(sys.argv) > 1 else 'firered'
S = json.load(open(R + f'build/rh_species_{VER}.json'))
EVO_LEVEL = 1
def bst(v): return sum(v[k] for k in ['baseHP', 'baseAttack', 'baseDefense', 'baseSpeed', 'baseSpAttack', 'baseSpDefense'])
samples = set()
for sp, v in S.items():
    if not (1 <= v['natDexNum'] <= 1025): continue
    for e in v['evolutions']:
        t = e['target']
        if e['method'] == EVO_LEVEL and t in S and e['param'] > 1:
            samples.add((bst(v), bst(S[t]), e['param']))
samples = sorted(samples)
def find(pre, post):
    ws = wsum = 0.0
    for sp, so, lv in samples:
        d = math.hypot(pre - sp, post - so)
        w = 1.0 if d == 0 else 1.0 / d
        adj = lv * ((pre / sp) ** 1.5 + (post / so) ** 3) / 2.0
        ws += adj * w; wsum += w
    return int(round(ws / wsum))
LO, HI, STEP = 100, 800, 10
N = (HI - LO) // STEP + 1
out = '// AUTO-GENERATED by tools/rh/gen_evo_levels.py - FVX estimated evolution levels by (pre BST, post BST)\n'
out += f'#define RH_EVO_BST_LO {LO}\n#define RH_EVO_BST_STEP {STEP}\n#define RH_EVO_BST_N {N}\n'
out += f'static const u8 sRhEvoLevelEstimate[{N}][{N}] = {{\n'
for i in range(N):
    row = [max(1, min(100, find(LO + i * STEP, LO + j * STEP))) for j in range(N)]
    out += '    {' + ','.join(map(str, row)) + '},\n'
out += '};\n'
open(R + 'src/data/rh_evo_levels.h', 'w').write(out)
print('samples', len(samples), 'e.g. 318->405', find(318, 405), '300->600', find(300, 600), '420->600', find(420,600))
