#!/usr/bin/env python3
"""Generates shop scripts, C tables, price overrides and map NPCs from shop_design.py.
Idempotent: safe to re-run."""
import json, re, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from shop_design import *
R = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')) + '/'

items_src = open(R + 'src/data/items.h').read()
all_items = set(re.findall(r'^    \[ITEM_(\w+)\]', items_src, re.M))

def sec_items(section):
    out, cur = [], None
    for line in items_src.split('\n'):
        m = re.match(r'^// (.+)$', line)
        if m: cur = m.group(1); continue
        m = re.match(r'^    \[ITEM_(\w+)\]', line)
        if m and cur == section: out.append(m.group(1))
    return out

MEGA = sec_items('Mega Stones')
ZCRYSTALS = sec_items('Z-Crystals')
BERRIES = [b for b in sec_items('Berries') if b not in BERRY_EXCLUDE]

def check(lst, what):
    bad = [i for i in lst if i not in all_items]
    if bad: raise SystemExit(f'{what}: unknown items {bad}')
for n, l in [('evo', EVO_ITEMS), ('herb', HERB_ITEMS), ('comp', CELADON_COMPETITIVE), ('forms', CELADON_FORMS),
             ('training', CELADON_TRAINING), ('local', LOCAL_SPECIALTIES),
             ('prog', [i for _, i in PROGRESSIVE_ALL_MARTS])] + [(k, [i for _, i in v]) for k, v in TOWN_THEMED.items()]:
    check(l, n)

# ---------------- price overrides in items.h ----------------
prices = dict(PRICE_OVERRIDES)
for m in MEGA: prices.setdefault(m, 10000)
for z in ZCRYSTALS: prices.setdefault(z, 10000)
src = items_src
for item, price in prices.items():
    if item not in all_items: continue
    pat = re.compile(r'(    \[ITEM_' + item + r'\] =\s*\{.*?\n        \.price = )([^\n]*?),( // RH)?\n', re.S)
    m = pat.search(src)
    if not m: raise SystemExit('no price field for ' + item)
    src = src[:m.start()] + m.group(1) + f'{price}, // RH\n' + src[m.end():]
if src != items_src:
    open(R + 'src/data/items.h', 'w').write(src)

# ---------------- shop scripts (.inc) ----------------
def lst(label, items):
    s = f'\t.align 2\n{label}::\n'
    for i in items: s += f'\t.2byte ITEM_{i}\n'
    return s + '\tpokemartlistend\n\n'

SPECIAL_IDS = {'RH_Items_Evo': 'RH_SPECIAL_EVO', 'RH_Items_Herb': 'RH_SPECIAL_HERB', 'RH_Items_Competitive': 'RH_SPECIAL_COMPETITIVE',
               'RH_Items_Forms': 'RH_SPECIAL_FORMS', 'RH_Items_Mega': 'RH_SPECIAL_MEGA', 'RH_Items_ZCrystal': 'RH_SPECIAL_ZCRYSTAL',
               'RH_Items_Training': 'RH_SPECIAL_TRAINING', 'RH_Items_Berries': 'RH_SPECIAL_BERRIES', 'RH_Items_Snacks': 'RH_SPECIAL_SNACKS'}
def shop(label, intro_text, list_label):
    # special RH_OpenSpecialShop randomizes the stock when "Randomize Special Shops" is on
    return (f'{label}::\n\tlock\n\tfaceplayer\n\tmsgbox {intro_text}\n\tmessage gText_HowMayIServeYou\n\twaitmessage\n'
            f'\tsetvar VAR_0x8004, {SPECIAL_IDS[list_label]}\n\tspecial RH_OpenSpecialShop\n'
            f'\tmsgbox gText_PleaseComeAgain\n\trelease\n\tend\n\n')

inc = '@ AUTO-GENERATED by tools/rh/gen_shops.py - do not edit by hand\n\n'
shops = [
    ('RH_EventScript_EvoShop', 'RH_Text_EvoShop', 'RH_Items_Evo', EVO_ITEMS),
    ('RH_EventScript_HerbShop', 'RH_Text_HerbShop', 'RH_Items_Herb', HERB_ITEMS),
    ('RH_EventScript_CeladonCompetitive', 'RH_Text_Competitive', 'RH_Items_Competitive', CELADON_COMPETITIVE),
    ('RH_EventScript_CeladonForms', 'RH_Text_Forms', 'RH_Items_Forms', CELADON_FORMS),
    ('RH_EventScript_CeladonMega', 'RH_Text_Mega', 'RH_Items_Mega', MEGA),
    ('RH_EventScript_CeladonZ', 'RH_Text_ZCrystal', 'RH_Items_ZCrystal', ZCRYSTALS),
    ('RH_EventScript_CeladonTraining', 'RH_Text_Training', 'RH_Items_Training', CELADON_TRAINING),
    ('RH_EventScript_CeladonBerries', 'RH_Text_Berries', 'RH_Items_Berries', BERRIES),
    ('RH_EventScript_CeladonSnacks', 'RH_Text_Snacks', 'RH_Items_Snacks', LOCAL_SPECIALTIES),
]
for label, text, ll, items in shops:
    inc += shop(label, text, ll) + lst(ll, items)
texts = {
    'RH_Text_EvoShop': "I deal in items that make POKéMON\\nevolve. Stones, cords, sweets…\\pWhatever your POKéMON needs!",
    'RH_Text_HerbShop': "Hohoho… Herbal medicine and mints,\\nfresh from all over the world.\\pBitter, but they work wonders.",
    'RH_Text_Competitive': "Welcome to the BATTLE GEAR counter.\\nOnly the finest held items here.",
    'RH_Text_Forms': "This counter carries rare artifacts\\nthat change a POKéMON's form.",
    'RH_Text_Mega': "MEGA STONES from every region!\\nYou'll need a MEGA RING to use them.",
    'RH_Text_ZCrystal': "Z-CRYSTALS, straight from ALOLA!\\nA Z-POWER RING unlocks their power.",
    'RH_Text_Training': "Serious trainers shop here.\\nWe help POKéMON reach full potential.",
    'RH_Text_Berries': "BERRIES from all over the world!\\nFresh picked, every one.",
    'RH_Text_Snacks': "Famous treats from every region!\\nPOKéMON love them.",
}
for k, v in texts.items():
    inc += f'{k}::\n\t.string "{v}$"\n\n'
open(R + 'data/scripts/rh_shops.inc', 'w').write(inc)

# ---------------- C tables ----------------
ids = [m[0] for m in MARTS]
h = '// AUTO-GENERATED by tools/rh/gen_shops.py - do not edit by hand\n'
h += '#ifndef GUARD_CONSTANTS_RH_SHOPS_H\n#define GUARD_CONSTANTS_RH_SHOPS_H\n\n'
for n, i in enumerate(ids): h += f'#define RH_MART_{i} {n}\n'
h += f'#define RH_MART_COUNT {len(ids)}\n\n#endif\n'
open(R + 'include/constants/rh_shops.h', 'w').write(h)

c = '// AUTO-GENERATED by tools/rh/gen_shops.py - do not edit by hand\n'
c += 'struct RhMartEntry { u8 minBadges; u16 item; };\n\n'
c += 'static const struct RhMartEntry sRhProgressive[] = {\n'
for b, i in PROGRESSIVE_ALL_MARTS: c += f'    {{{b}, ITEM_{i}}},\n'
c += '};\n\n'
for mid, _, _ in MARTS:
    c += f'static const struct RhMartEntry sRhThemed_{mid}[] = {{\n'
    for b, i in TOWN_THEMED.get(mid, []): c += f'    {{{b}, ITEM_{i}}},\n'
    c += '    {0, ITEM_NONE},\n};\n'
for _, _, base in MARTS: c += f'extern const u16 {base}[];\n'
c += '\nstatic const struct { const u16 *base; const struct RhMartEntry *themed; } sRhMarts[RH_MART_COUNT] = {\n'
for mid, _, base in MARTS: c += f'    [RH_MART_{mid}] = {{{base}, sRhThemed_{mid}}},\n'
c += '};\n'
open(R + 'src/data/rh_shops.h', 'w').write(c)

# ---------------- clerk scripts -> progressive mart ----------------
for mid, mapname, base in MARTS:
    p = R + f'data/maps/{mapname}/scripts.inc'
    s = open(p).read()
    new = f'\tsetvar VAR_0x8004, RH_MART_{mid}\n\tspecial RH_OpenMart\n'
    s2 = s.replace(f'\tpokemart {base}\n', new)
    if s2 == s and new not in s: raise SystemExit('clerk not found in ' + mapname)
    open(p, 'w').write(s2)

# ---------------- map NPCs ----------------
def add_obj(mapname, script, gfx, x, y, move):
    p = R + f'data/maps/{mapname}/map.json'
    m = json.load(open(p))
    objs = m.setdefault('object_events', [])
    objs[:] = [o for o in objs if o.get('script') != script]
    for o in objs:
        if o['x'] == x and o['y'] == y: raise SystemExit(f'{mapname}: tile {x},{y} occupied')
    objs.append({"type": "object", "graphics_id": gfx, "x": x, "y": y, "elevation": 3,
                 "movement_type": move, "movement_range_x": 0, "movement_range_y": 0,
                 "trainer_type": "TRAINER_TYPE_NONE", "trainer_sight_or_berry_tree_id": "0",
                 "script": script, "flag": "0"})
    json.dump(m, open(p, 'w'), indent=2); open(p, 'a').write('\n')

for mapname, (x, y) in EVO_NPC_POS.items():
    face = 'MOVEMENT_TYPE_FACE_UP' if mapname == 'TrainerTower_Lobby_Frlg' else 'MOVEMENT_TYPE_FACE_RIGHT'
    add_obj(mapname, 'RH_EventScript_EvoShop', 'OBJ_EVENT_GFX_SCIENTIST', x, y, face)
add_obj('CeladonCity_DepartmentStore_4F_Frlg', 'RH_EventScript_EvoShop', 'OBJ_EVENT_GFX_SCIENTIST', 12, 8, 'MOVEMENT_TYPE_FACE_LEFT')
add_obj('LavenderTown_Mart_Frlg', 'RH_EventScript_HerbShop', 'OBJ_EVENT_GFX_OLD_WOMAN_FRLG', 1, 5, 'MOVEMENT_TYPE_FACE_RIGHT')
add_obj('CeladonCity_DepartmentStore_2F_Frlg', 'RH_EventScript_CeladonCompetitive', 'OBJ_EVENT_GFX_CLERK', 1, 7, 'MOVEMENT_TYPE_FACE_RIGHT')
add_obj('CeladonCity_DepartmentStore_3F_Frlg', 'RH_EventScript_CeladonForms', 'OBJ_EVENT_GFX_CLERK', 9, 9, 'MOVEMENT_TYPE_FACE_LEFT')
add_obj('CeladonCity_DepartmentStore_4F_Frlg', 'RH_EventScript_CeladonMega', 'OBJ_EVENT_GFX_CLERK', 1, 13, 'MOVEMENT_TYPE_FACE_UP')
add_obj('CeladonCity_DepartmentStore_4F_Frlg', 'RH_EventScript_CeladonZ', 'OBJ_EVENT_GFX_CLERK', 5, 13, 'MOVEMENT_TYPE_FACE_UP')
add_obj('CeladonCity_DepartmentStore_5F_Frlg', 'RH_EventScript_CeladonTraining', 'OBJ_EVENT_GFX_GENTLEMAN_FRLG', 4, 10, 'MOVEMENT_TYPE_FACE_DOWN')
add_obj('CeladonCity_DepartmentStore_Roof_Frlg', 'RH_EventScript_CeladonBerries', 'OBJ_EVENT_GFX_WOMAN_3_FRLG', 12, 7, 'MOVEMENT_TYPE_FACE_DOWN')
add_obj('CeladonCity_DepartmentStore_Roof_Frlg', 'RH_EventScript_CeladonSnacks', 'OBJ_EVENT_GFX_CHEF', 3, 7, 'MOVEMENT_TYPE_FACE_DOWN')
print('shops generated:', {l: len(i) for _, _, l, i in shops})
