#!/usr/bin/env python3
"""Generates move/item/trainer/static tables for the in-game randomizer.
Output: src/data/rh_randomizer_tables.h"""
import json, os, re, sys, glob
R = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')) + '/'
VER = sys.argv[1] if len(sys.argv) > 1 else 'firered'
M = json.load(open(R + f'build/rh_moves_{VER}.json'))
S = json.load(open(R + f'build/rh_species_{VER}.json'))
MAP_SUFFIX = '_Frlg' if VER == 'firered' else ''
out = '// AUTO-GENERATED by tools/rh/gen_randomizer_tables.py - do not edit by hand\n\n'

# ---------------- moves ----------------
moves_h = open(R + 'include/constants/moves.h').read()
first_z = int(re.search(r'MOVE_\w+\s*=\s*(\d+),\s*\n\s*MOVES_COUNT_GEN9', moves_h).group(1)) + 1
TYPES = ['TYPE_NORMAL', 'TYPE_FIGHTING', 'TYPE_FLYING', 'TYPE_POISON', 'TYPE_GROUND', 'TYPE_ROCK', 'TYPE_BUG', 'TYPE_GHOST',
         'TYPE_STEEL', 'TYPE_FIRE', 'TYPE_WATER', 'TYPE_GRASS', 'TYPE_ELECTRIC', 'TYPE_PSYCHIC', 'TYPE_ICE', 'TYPE_DRAGON',
         'TYPE_DARK', 'TYPE_FAIRY']
# FVX: only Struggle (and moves that can't work here) are banned from random picks.
UNUSABLE = {'MOVE_STRUGGLE', 'MOVE_HYPERSPACE_FURY', 'MOVE_AURA_WHEEL', 'MOVE_DARK_VOID'}   # Dark Void: Darkrai only (Gen 7+)
# FVX "No Game-Breaking Moves": Sonic Boom and Dragon Rage; with Gen 1 rules also OHKO moves and Spore.
BROKEN = {'MOVE_SONIC_BOOM', 'MOVE_DRAGON_RAGE'}
GEN1_BROKEN_EFFECTS = {'EFFECT_OHKO'}
GEN1_BROKEN = {'MOVE_SPORE'}
# FVX GlobalConstants.bannedForDamagingMove: never used as a forced / "good" attack.
NO_DAMAGING = {'SELF_DESTRUCT', 'DREAM_EATER', 'EXPLOSION', 'SNORE', 'FALSE_SWIPE', 'FUTURE_SIGHT', 'FAKE_OUT', 'FOCUS_PUNCH',
               'DOOM_DESIRE', 'FEINT', 'LAST_RESORT', 'SUCKER_PUNCH', 'CONSTRICT', 'RAGE', 'ROLLOUT', 'ICE_BALL',
               'SYNCHRONOISE', 'SHELL_TRAP', 'FOUL_PLAY', 'SPIT_UP', 'SONIC_BOOM', 'DRAGON_RAGE', 'HORN_DRILL',
               'GUILLOTINE', 'FISSURE', 'SHEER_COLD', 'MISTY_EXPLOSION', 'MIND_BLOWN', 'STEEL_BEAM', 'BELCH'}
pool = []
for name, d in M.items():
    i = d['id']
    if i == 0 or i >= first_z or name in UNUSABLE or d['effectName'] == 'EFFECT_PLACEHOLDER' or d['type'] not in TYPES: continue
    broken = name in BROKEN
    g1 = d['effectName'] in GEN1_BROKEN_EFFECTS or name in GEN1_BROKEN
    nodmg = name[5:] in NO_DAMAGING
    hits = 3 if d['multiHit'] else max(1, d['strikeCount'])
    pool.append((i, name, broken, g1, nodmg, hits))
pool.sort()
out += 'struct RhMove { u16 move; u8 broken:1; u8 gen1Broken:1; u8 noDamaging:1; u8 hits:4; u8 pad:1; };\n'
out += f'#define RH_MOVE_COUNT {len(pool)}\nstatic const struct RhMove sRhMoves[RH_MOVE_COUNT] = {{\n'
for i, n, br, g1, nd, h in pool: out += f'    {{{n}, {int(br)}, {int(g1)}, {int(nd)}, {h}, 0}},\n'
out += '};\n'
out += 'static const u8 sRhTypes[] = { ' + ', '.join(TYPES) + ' };\n\n'

# ---------------- items ----------------
items_src = open(R + 'src/data/items.h').read()
sections, cur = {}, None
for line in items_src.split('\n'):
    m = re.match(r'^// (.+)$', line)
    if m: cur = m.group(1); continue
    m = re.match(r'^    \[ITEM_(\w+)\]', line)
    if m: sections.setdefault(cur, []).append(m.group(1))
GOOD_SECTIONS = ['Poké Balls', 'Medicine', 'Vitamins', 'EV Feathers', 'Mints', 'Candies', 'Encounter Modifiers', 'X items',
                 'Treasures', 'Evolution items', 'Gems', 'Incenses', 'Power items', 'Type-enhancing items', 'Choice items',
                 'Status Orbs', 'Weather Rocks', 'Terrain Seeds', 'Type-activated stat modifiers', 'Miscellaneous Held items',
                 'Berries', 'Species-specific Stat-enhancing items', 'Ability Modifiers', 'Mega Stones', 'Z-Crystals', 'Plates',
                 'Memories', 'Drives', 'Local specialties', 'Medicinal Flutes', 'Encounter-modifying Flutes', 'Nectars']
BAD_ITEMS = {'STRANGE_BALL', 'MASTER_BALL', 'CHERISH_BALL', 'PARK_BALL', 'SAFARI_BALL', 'DREAM_BALL', 'BEAST_BALL', 'SPORT_BALL',
             'DYNAMAX_CANDY', 'ENIGMA_BERRY_E_READER', 'SOUL_DEW', 'RUSTED_SWORD', 'RUSTED_SHIELD', 'EXP_SHARE',
             'RELIC_COPPER', 'RELIC_SILVER', 'RELIC_VASE', 'RELIC_BAND', 'RELIC_STATUE', 'RELIC_CROWN', 'SHOAL_SALT', 'SHOAL_SHELL',
             'ODD_KEYSTONE', 'STRANGE_SOUVENIR', 'RED_SHARD', 'BLUE_SHARD', 'YELLOW_SHARD', 'GREEN_SHARD', 'HEART_SCALE'}
JUNK = {'TINY_MUSHROOM', 'PRETTY_FEATHER', 'HONEY', 'BLACK_FLUTE', 'WHITE_FLUTE', 'BLUE_FLUTE', 'YELLOW_FLUTE', 'RED_FLUTE',
        'FRESH_WATER', 'SODA_POP', 'BERRY_JUICE', 'LAGGING_TAIL', 'IRON_BALL', 'RING_TARGET', 'STICKY_BARB', 'FULL_INCENSE',
        'BLACK_SLUDGE', 'CLEANSE_TAG', 'SMOKE_BALL', 'SOOTHE_BELL', 'POKE_DOLL', 'FLUFFY_TAIL', 'POKE_TOY'}
item_pool = []
for sec in GOOD_SECTIONS:
    for it in sections.get(sec, []):
        if it in BAD_ITEMS: continue
        item_pool.append((it, int(it in JUNK)))
out += 'struct RhItem { u16 item; u8 junk; };\n'
out += f'#define RH_ITEM_COUNT {len(item_pool)}\nstatic const struct RhItem sRhItems[RH_ITEM_COUNT] = {{\n'
for it, j in item_pool: out += f'    {{ITEM_{it}, {j}}},\n'
out += '};\n\n'

# ---------------- field items (item balls + hidden) ----------------
ball_items = dict(re.findall(r'^(\w+)::\n\tfinditem (ITEM_\w+)', open(R + 'data/scripts/item_ball_scripts_frlg.inc' if VER == 'firered' else R + 'data/scripts/item_ball_scripts.inc').read(), re.M))
field = []
for mj in sorted(glob.glob(R + f'data/maps/*{MAP_SUFFIX}/map.json')):
    m = json.load(open(mj))
    for o in m.get('object_events', []):
        sc = o.get('script')
        if sc in ball_items and o.get('flag', '0') not in ('0', ''):
            field.append((o['flag'], ball_items[sc]))
    for b in m.get('bg_events', []):
        if b.get('type') == 'hidden_item':
            field.append((b['flag'], b['item']))
field = sorted(set(field))
out += '// Every item ball / hidden item in the game, keyed by its flag (for "shuffle" mode).\n'
out += 'struct RhFieldItem { u16 flag; u16 item; };\n'
out += f'#define RH_FIELD_ITEM_COUNT {len(field)}\nstatic const struct RhFieldItem sRhFieldItems[RH_FIELD_ITEM_COUNT] = {{\n'
for f, it in field: out += f'    {{{f}, {it}}},\n'
out += '};\n\n'

# ---------------- gym / elite four type themes ----------------
GYMS = {'PewterCity_Gym': 'TYPE_ROCK', 'CeruleanCity_Gym': 'TYPE_WATER', 'VermilionCity_Gym': 'TYPE_ELECTRIC',
        'CeladonCity_Gym': 'TYPE_GRASS', 'FuchsiaCity_Gym': 'TYPE_POISON', 'SaffronCity_Gym': 'TYPE_PSYCHIC',
        'CinnabarIsland_Gym': 'TYPE_FIRE', 'ViridianCity_Gym': 'TYPE_GROUND',
        'PokemonLeague_LoreleisRoom': 'TYPE_ICE', 'PokemonLeague_BrunosRoom': 'TYPE_FIGHTING',
        'PokemonLeague_AgathasRoom': 'TYPE_GHOST', 'PokemonLeague_LancesRoom': 'TYPE_DRAGON'}
themes = []
for mp, t in GYMS.items():
    p = R + f'data/maps/{mp}{MAP_SUFFIX}/scripts.inc'
    for tr in sorted(set(re.findall(r'trainerbattle\w*\s+(TRAINER_\w+)', open(p).read()))):
        themes.append((tr, t))
if VER == 'firered':
    themes += [('TRAINER_BOSS_GIOVANNI', 'TYPE_GROUND'), ('TRAINER_BOSS_GIOVANNI_2', 'TYPE_GROUND')]   # FVX groups them with his gym
out += 'struct RhTrainerTheme { u16 trainer; u8 type; };\n'
out += 'static const struct RhTrainerTheme sRhTrainerThemes[] = {\n'
for tr, t in themes: out += f'    {{{tr}, {t}}},\n'
out += '};\n\n'

# ---------------- static / gift Pokemon ----------------
statics = set()
for sc in glob.glob(R + f'data/maps/*{MAP_SUFFIX}/scripts.inc'):
    if 'ProfessorOaksLab' in sc: continue
    txt = open(sc).read()
    for m in re.finditer(r'^\s*(?:givemon|setwildbattle|giveegg)\s+(SPECIES_\w+)', txt, re.M):
        statics.add(m.group(1))
    for m in re.finditer(r'^\s*setvar\s+VAR_\w+,\s*(SPECIES_\w+)', txt, re.M):
        statics.add(m.group(1))
for sc in glob.glob(R + 'data/scripts/*.inc'):
    txt = open(sc).read()
    for m in re.finditer(r'^\s*(?:givemon|setwildbattle|giveegg)\s+(SPECIES_\w+)', txt, re.M):
        statics.add(m.group(1))
ALIAS = dict(re.findall(r'^\s*(SPECIES_\w+)\s*=\s*(SPECIES_\w+)\s*,', open(R + 'include/constants/species.h').read(), re.M))
def canon(n):
    for _ in range(4):
        if n in S: return n
        n = ALIAS.get(n, n)
    return n
STARTERS = {'SPECIES_BULBASAUR', 'SPECIES_CHARMANDER', 'SPECIES_SQUIRTLE', 'SPECIES_TREECKO', 'SPECIES_TORCHIC', 'SPECIES_MUDKIP'}
statics = sorted({canon(s) for s in statics if s not in STARTERS and canon(s) in S and S[canon(s)]['natDexNum'] and s not in ('SPECIES_NONE', 'SPECIES_EGG')},
                 key=lambda n: S[n]['id'])
# Every static encounter / gift with its map (FVX treats each one separately and never repeats a replacement).
enc = []
for sc in sorted(glob.glob(R + f'data/maps/*{MAP_SUFFIX}/scripts.inc')):
    if 'ProfessorOaksLab' in sc: continue
    mj = os.path.join(os.path.dirname(sc), 'map.json')
    if not os.path.exists(mj): continue
    mapid = json.load(open(mj))['id']
    txt = open(sc).read()
    for m in re.finditer(r'^\s*(?:givemon|setwildbattle|giveegg|seteventmon)\s+(SPECIES_\w+)|^\s*setvar\s+VAR_TEMP_1,\s*(SPECIES_\w+)', txt, re.M):
        s = canon(m.group(1) or m.group(2))
        if s in S and (mapid, s) not in enc and s != 'SPECIES_TOGEPI':   # FVX leaves the Togepi Egg alone
            enc.append((mapid, s))
for s in ('SPECIES_RAIKOU', 'SPECIES_ENTEI', 'SPECIES_SUICUNE'):
    enc.append(('ROAMER', s))
out += 'struct RhStaticEncounter { u16 map; u16 species; };\n#define RH_STATIC_MAP_ROAMER 0xFFFE\n'
out += f'#define RH_STATIC_ENCOUNTER_COUNT {len(enc)}\nstatic const struct RhStaticEncounter sRhStaticEncounters[] = {{\n'
for mp, s in enc:
    out += f'    {{{"RH_STATIC_MAP_ROAMER" if mp == "ROAMER" else mp}, {s}}},\n'
out += '};\n'
print('static encounters', len(enc), enc)
out += '// Species given/fought through scripts (gifts, static encounters, game corner prizes...).\n'
out += 'static const u16 sRhStaticSpecies[] = {\n'
for s in statics: out += f'    {s},\n'
out += '};\n'
open(R + 'src/data/rh_randomizer_tables.h', 'w').write(out)
print('moves', len(pool), 'items', len(item_pool), 'field items', len(field), 'trainer themes', len(themes), 'statics', len(statics))
print('statics:', [s[8:] for s in statics])

# ---------------- wild encounter (map, area, species) pairs: zones, Catch Em' All, Balance Low Level ----------------
frlg_maps = {}
for mj in glob.glob(R + f'data/maps/*{MAP_SUFFIX}/map.json'):
    j = json.load(open(mj))
    frlg_maps[j['id']] = j.get('region_map_section', 'MAPSEC_NONE')
W = json.load(open(R + 'src/data/wild_encounters.json'))['wild_encounter_groups'][0]
AREAS = ['land_mons', 'water_mons', 'rock_smash_mons', 'fishing_mons']
low = {}
for e in W['encounters']:
    if e['map'] not in frlg_maps or ('LeafGreen' in e['base_label'] and VER == 'firered'):
        continue
    for ai, k in enumerate(AREAS):
        if k in e:
            for m in e[k]['mons']:
                key = (e['map'], ai, canon(m['species']))
                lv = (m['min_level'] + m['max_level']) // 2
                low[key] = min(low.get(key, 100), lv)
pairs = sorted(low)
# Dense Catch Em' All ranks per zone mode: 0 whole game, 1 whole game split, 2 location, 3 location split,
# 4 map, 5 map split, 6 encounter set. Same (zone, species) -> same rank; ranks count up from 0.
def zone_species(mode, mp, ai, sp):
    sec = frlg_maps[mp]
    return [(sp,), (ai, sp), (sec, sp), (sec, ai, sp), (mp, sp), (mp, ai, sp), (mp, ai, sp)][mode]
ranks = []
for mode in range(7):
    seen = {}
    col = []
    for mp, ai, sp in pairs:
        k = zone_species(mode, mp, ai, sp)
        if k not in seen: seen[k] = len(seen)
        col.append(seen[k])
    ranks.append(col)
out2 = '\n// Every (map, area, species) wild encounter in the game with its region map section and lowest level.\n'
out2 += 'struct RhWildPair { u16 map; u16 species; u8 area; u8 low; u8 mapsec; u8 pad; };\n'
out2 += f'#define RH_WILD_PAIR_COUNT {len(pairs)}\nstatic const struct RhWildPair sRhWildPairs[RH_WILD_PAIR_COUNT] = {{\n'
for mp, ai, sp in pairs: out2 += f'    {{{mp}, {sp}, {ai}, {low[(mp, ai, sp)]}, {frlg_maps[mp]}, 0}},\n'
out2 += '};\n'
out2 += '// Catch Em\' All ranks: [pair][0 whole game, 1 +split, 2 location, 3 +split, 4 map, 5 +split, 6 set]\n'
out2 += f'static const u16 sRhWildRank[RH_WILD_PAIR_COUNT][7] = {{\n'
for n in range(len(pairs)): out2 += '    {' + ', '.join(str(ranks[m][n]) for m in range(7)) + '},\n'
out2 += '};\n'
open(R + 'src/data/rh_randomizer_tables.h', 'a').write(out2)
print('wild pairs', len(pairs), 'ranks', [max(c) + 1 for c in ranks])
