#!/usr/bin/env python3
"""Word lists for random move / trainer / trainer class / nickname generation, taken from UPR FVX (GPL-3.0)
random/src/main/resources/data. Output: src/data/rh_names.h"""
import os, re
R = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')) + '/'
FVX = '/home/claude/work/fvx/random/src/main/resources/data/'
def words(line):
    return re.findall(r'\(([^)]*)\)', line)
def section(path):
    out = {}
    for line in open(path, encoding='utf-8', errors='replace'):
        m = re.match(r'\[(\w+)\]\s*(.*)', line.strip())
        if m:
            out[m.group(1)] = list(dict.fromkeys(words(m.group(2))))
    return out
def plain(path, maxlen):
    return [l.strip() for l in open(path, encoding='utf-8') if l.strip() and len(l.strip()) <= maxlen]
cat = section(FVX + 'move_names/CatMoveNames.txt')
typ = section(FVX + 'move_names/TypeMoveNames.txt')
def carr(name, items):
    s = f'static const u8 *const {name}[] = {{\n'
    for i in items:
        s += '    COMPOUND_STRING("' + i.replace('"', '') + '"),\n'
    return s + '};\n'
c = '// AUTO-GENERATED by tools/rh/gen_names.py from UPR FVX word lists (GPL-3.0) - do not edit by hand\n'
TYPES = ['NORMAL', 'FIGHTING', 'FLYING', 'POISON', 'GROUND', 'ROCK', 'BUG', 'GHOST', 'STEEL', 'FIRE', 'WATER', 'GRASS',
         'ELECTRIC', 'PSYCHIC', 'ICE', 'DRAGON', 'DARK', 'FAIRY']
for t in TYPES:
    c += carr(f'sRhMoveWords_{t}', [w for w in typ[t] if len(w) <= 9])
c += 'static const u8 *const *const sRhMoveTypeWords[] = { ' + ', '.join(f'sRhMoveWords_{t}' for t in TYPES) + ' };\n'
c += 'static const u8 sRhMoveTypeWordCounts[] = { ' + ', '.join(f'ARRAY_COUNT(sRhMoveWords_{t})' for t in TYPES) + ' };\n'
for k in ['PHYSICAL', 'SPECIAL', 'STATUS']:
    c += carr(f'sRhMoveWords_{k}', [w for w in cat[k] if len(w) <= 8])
c += carr('sRhTrainerClassNames', plain(FVX + 'trainer_and_mon_names/TrainerClasses.txt', 12))
c += carr('sRhTrainerNames', plain(FVX + 'trainer_and_mon_names/TrainerNames.txt', 10))
c += carr('sRhNicknames', plain(FVX + 'trainer_and_mon_names/PokemonNicknames.txt', 10))
open(R + 'src/data/rh_names.h', 'w').write(c)
print('ok')
