// AUTO-GENERATED by tools/rh/gen_player_graphics.py - do not edit by hand
// Player graphics converted from UPR FVX graphics packs (see graphics/rh_player/CREDITS.txt).
static const u16 sRhPg0_Normal[] = INCGFX_U16("graphics/rh_player/ethan_frlg/normal.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg0_Surf[] = INCGFX_U16("graphics/rh_player/ethan_frlg/surf.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg0_Bike[] = INCGFX_U16("graphics/rh_player/ethan_frlg/bike.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg0_Fish[] = INCGFX_U16("graphics/rh_player/ethan_frlg/fish.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg0_Item[] = INCGFX_U16("graphics/rh_player/ethan_frlg/item.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg0_ItemBike[] = INCGFX_U16("graphics/rh_player/ethan_frlg/itembike.png", ".4bpp", "-mwidth 4 -mheight 4");
const u16 gRhPlayerPal0[] = INCGFX_U16("graphics/rh_player/ethan_frlg/normal.png", ".gbapal");
static const u32 sRhPg0_Front[] = INCGFX_U32("graphics/rh_player/ethan_frlg/front.png", ".4bpp.smol");
static const u16 sRhPg0_FrontPal[] = INCGFX_U16("graphics/rh_player/ethan_frlg/front.png", ".gbapal");
static const u32 sRhPg0_Oak[] = INCGFX_U32("graphics/rh_player/ethan_frlg/oak.png", ".8bpp.smol");
static const u8 sRhPg0_Back[] = INCGFX_U8("graphics/rh_player/ethan_frlg/back.png", ".4bpp");
static const u16 sRhPg0_BackPal[] = INCGFX_U16("graphics/rh_player/ethan_frlg/back.png", ".gbapal");
static const struct SpriteFrameImage sRhPg0_PicNormal[] = {
    overworld_frame(sRhPg0_Normal, 2, 4, 0),
    overworld_frame(sRhPg0_Normal, 2, 4, 1),
    overworld_frame(sRhPg0_Normal, 2, 4, 2),
    overworld_frame(sRhPg0_Normal, 2, 4, 3),
    overworld_frame(sRhPg0_Normal, 2, 4, 4),
    overworld_frame(sRhPg0_Normal, 2, 4, 5),
    overworld_frame(sRhPg0_Normal, 2, 4, 6),
    overworld_frame(sRhPg0_Normal, 2, 4, 7),
    overworld_frame(sRhPg0_Normal, 2, 4, 8),
    overworld_frame(sRhPg0_Normal, 2, 4, 9),
    overworld_frame(sRhPg0_Normal, 2, 4, 10),
    overworld_frame(sRhPg0_Normal, 2, 4, 11),
    overworld_frame(sRhPg0_Normal, 2, 4, 12),
    overworld_frame(sRhPg0_Normal, 2, 4, 13),
    overworld_frame(sRhPg0_Normal, 2, 4, 14),
    overworld_frame(sRhPg0_Normal, 2, 4, 15),
    overworld_frame(sRhPg0_Normal, 2, 4, 16),
    overworld_frame(sRhPg0_Normal, 2, 4, 17),
    overworld_frame(sRhPg0_Normal, 2, 4, 18),
    overworld_frame(sRhPg0_Normal, 2, 4, 19),
};
static const struct SpriteFrameImage sRhPg0_PicSurf[] = {
    overworld_frame(sRhPg0_Surf, 2, 4, 0),
    overworld_frame(sRhPg0_Surf, 2, 4, 1),
    overworld_frame(sRhPg0_Surf, 2, 4, 2),
    overworld_frame(sRhPg0_Surf, 2, 4, 0),
    overworld_frame(sRhPg0_Surf, 2, 4, 0),
    overworld_frame(sRhPg0_Surf, 2, 4, 1),
    overworld_frame(sRhPg0_Surf, 2, 4, 1),
    overworld_frame(sRhPg0_Surf, 2, 4, 2),
    overworld_frame(sRhPg0_Surf, 2, 4, 2),
    overworld_frame(sRhPg0_Surf, 2, 4, 0),
    overworld_frame(sRhPg0_Surf, 2, 4, 1),
    overworld_frame(sRhPg0_Surf, 2, 4, 2),
};
static const struct SpriteFrameImage sRhPg0_PicBike[] = { overworld_ascending_frames(sRhPg0_Bike, 4, 4) };
static const struct SpriteFrameImage sRhPg0_PicFish[] = { overworld_ascending_frames(sRhPg0_Fish, 4, 4) };
static const struct SpriteFrameImage sRhPg0_PicItem[] = { overworld_ascending_frames(sRhPg0_Item, 2, 4) };
static const struct SpriteFrameImage sRhPg0_PicItemBike[] = { overworld_ascending_frames(sRhPg0_ItemBike, 4, 4) };

static const u16 sRhPg1_Normal[] = INCGFX_U16("graphics/rh_player/kris_frlg/normal.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg1_Surf[] = INCGFX_U16("graphics/rh_player/kris_frlg/surf.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg1_Bike[] = INCGFX_U16("graphics/rh_player/kris_frlg/bike.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg1_Fish[] = INCGFX_U16("graphics/rh_player/kris_frlg/fish.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg1_Item[] = INCGFX_U16("graphics/rh_player/kris_frlg/item.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg1_ItemBike[] = INCGFX_U16("graphics/rh_player/kris_frlg/itembike.png", ".4bpp", "-mwidth 4 -mheight 4");
const u16 gRhPlayerPal1[] = INCGFX_U16("graphics/rh_player/kris_frlg/normal.png", ".gbapal");
static const u32 sRhPg1_Front[] = INCGFX_U32("graphics/rh_player/kris_frlg/front.png", ".4bpp.smol");
static const u16 sRhPg1_FrontPal[] = INCGFX_U16("graphics/rh_player/kris_frlg/front.png", ".gbapal");
static const u32 sRhPg1_Oak[] = INCGFX_U32("graphics/rh_player/kris_frlg/oak.png", ".8bpp.smol");
static const u8 sRhPg1_Back[] = INCGFX_U8("graphics/rh_player/kris_frlg/back.png", ".4bpp");
static const u16 sRhPg1_BackPal[] = INCGFX_U16("graphics/rh_player/kris_frlg/back.png", ".gbapal");
static const struct SpriteFrameImage sRhPg1_PicNormal[] = {
    overworld_frame(sRhPg1_Normal, 2, 4, 0),
    overworld_frame(sRhPg1_Normal, 2, 4, 1),
    overworld_frame(sRhPg1_Normal, 2, 4, 2),
    overworld_frame(sRhPg1_Normal, 2, 4, 3),
    overworld_frame(sRhPg1_Normal, 2, 4, 4),
    overworld_frame(sRhPg1_Normal, 2, 4, 5),
    overworld_frame(sRhPg1_Normal, 2, 4, 6),
    overworld_frame(sRhPg1_Normal, 2, 4, 7),
    overworld_frame(sRhPg1_Normal, 2, 4, 8),
    overworld_frame(sRhPg1_Normal, 2, 4, 9),
    overworld_frame(sRhPg1_Normal, 2, 4, 10),
    overworld_frame(sRhPg1_Normal, 2, 4, 11),
    overworld_frame(sRhPg1_Normal, 2, 4, 12),
    overworld_frame(sRhPg1_Normal, 2, 4, 13),
    overworld_frame(sRhPg1_Normal, 2, 4, 14),
    overworld_frame(sRhPg1_Normal, 2, 4, 15),
    overworld_frame(sRhPg1_Normal, 2, 4, 16),
    overworld_frame(sRhPg1_Normal, 2, 4, 17),
    overworld_frame(sRhPg1_Normal, 2, 4, 18),
    overworld_frame(sRhPg1_Normal, 2, 4, 19),
};
static const struct SpriteFrameImage sRhPg1_PicSurf[] = {
    overworld_frame(sRhPg1_Surf, 2, 4, 0),
    overworld_frame(sRhPg1_Surf, 2, 4, 1),
    overworld_frame(sRhPg1_Surf, 2, 4, 2),
    overworld_frame(sRhPg1_Surf, 2, 4, 0),
    overworld_frame(sRhPg1_Surf, 2, 4, 0),
    overworld_frame(sRhPg1_Surf, 2, 4, 1),
    overworld_frame(sRhPg1_Surf, 2, 4, 1),
    overworld_frame(sRhPg1_Surf, 2, 4, 2),
    overworld_frame(sRhPg1_Surf, 2, 4, 2),
    overworld_frame(sRhPg1_Surf, 2, 4, 0),
    overworld_frame(sRhPg1_Surf, 2, 4, 1),
    overworld_frame(sRhPg1_Surf, 2, 4, 2),
};
static const struct SpriteFrameImage sRhPg1_PicBike[] = { overworld_ascending_frames(sRhPg1_Bike, 4, 4) };
static const struct SpriteFrameImage sRhPg1_PicFish[] = { overworld_ascending_frames(sRhPg1_Fish, 4, 4) };
static const struct SpriteFrameImage sRhPg1_PicItem[] = { overworld_ascending_frames(sRhPg1_Item, 2, 4) };
static const struct SpriteFrameImage sRhPg1_PicItemBike[] = { overworld_ascending_frames(sRhPg1_ItemBike, 4, 4) };

static const u16 sRhPg2_Normal[] = INCGFX_U16("graphics/rh_player/red_fr/normal.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg2_Surf[] = INCGFX_U16("graphics/rh_player/red_fr/surf.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg2_Bike[] = INCGFX_U16("graphics/rh_player/red_fr/bike.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg2_Fish[] = INCGFX_U16("graphics/rh_player/red_fr/fish.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg2_Item[] = INCGFX_U16("graphics/rh_player/red_fr/item.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg2_ItemBike[] = INCGFX_U16("graphics/rh_player/red_fr/itembike.png", ".4bpp", "-mwidth 4 -mheight 4");
const u16 gRhPlayerPal2[] = INCGFX_U16("graphics/rh_player/red_fr/normal.png", ".gbapal");
static const u32 sRhPg2_Front[] = INCGFX_U32("graphics/rh_player/red_fr/front.png", ".4bpp.smol");
static const u16 sRhPg2_FrontPal[] = INCGFX_U16("graphics/rh_player/red_fr/front.png", ".gbapal");
static const u32 sRhPg2_Oak[] = INCGFX_U32("graphics/rh_player/red_fr/oak.png", ".8bpp.smol");
static const u8 sRhPg2_Back[] = INCGFX_U8("graphics/rh_player/red_fr/back.png", ".4bpp");
static const u16 sRhPg2_BackPal[] = INCGFX_U16("graphics/rh_player/red_fr/back.png", ".gbapal");
static const struct SpriteFrameImage sRhPg2_PicNormal[] = {
    overworld_frame(sRhPg2_Normal, 2, 4, 0),
    overworld_frame(sRhPg2_Normal, 2, 4, 1),
    overworld_frame(sRhPg2_Normal, 2, 4, 2),
    overworld_frame(sRhPg2_Normal, 2, 4, 3),
    overworld_frame(sRhPg2_Normal, 2, 4, 4),
    overworld_frame(sRhPg2_Normal, 2, 4, 5),
    overworld_frame(sRhPg2_Normal, 2, 4, 6),
    overworld_frame(sRhPg2_Normal, 2, 4, 7),
    overworld_frame(sRhPg2_Normal, 2, 4, 8),
    overworld_frame(sRhPg2_Normal, 2, 4, 9),
    overworld_frame(sRhPg2_Normal, 2, 4, 10),
    overworld_frame(sRhPg2_Normal, 2, 4, 11),
    overworld_frame(sRhPg2_Normal, 2, 4, 12),
    overworld_frame(sRhPg2_Normal, 2, 4, 13),
    overworld_frame(sRhPg2_Normal, 2, 4, 14),
    overworld_frame(sRhPg2_Normal, 2, 4, 15),
    overworld_frame(sRhPg2_Normal, 2, 4, 16),
    overworld_frame(sRhPg2_Normal, 2, 4, 17),
    overworld_frame(sRhPg2_Normal, 2, 4, 18),
    overworld_frame(sRhPg2_Normal, 2, 4, 19),
};
static const struct SpriteFrameImage sRhPg2_PicSurf[] = {
    overworld_frame(sRhPg2_Surf, 2, 4, 0),
    overworld_frame(sRhPg2_Surf, 2, 4, 1),
    overworld_frame(sRhPg2_Surf, 2, 4, 2),
    overworld_frame(sRhPg2_Surf, 2, 4, 0),
    overworld_frame(sRhPg2_Surf, 2, 4, 0),
    overworld_frame(sRhPg2_Surf, 2, 4, 1),
    overworld_frame(sRhPg2_Surf, 2, 4, 1),
    overworld_frame(sRhPg2_Surf, 2, 4, 2),
    overworld_frame(sRhPg2_Surf, 2, 4, 2),
    overworld_frame(sRhPg2_Surf, 2, 4, 0),
    overworld_frame(sRhPg2_Surf, 2, 4, 1),
    overworld_frame(sRhPg2_Surf, 2, 4, 2),
};
static const struct SpriteFrameImage sRhPg2_PicBike[] = { overworld_ascending_frames(sRhPg2_Bike, 4, 4) };
static const struct SpriteFrameImage sRhPg2_PicFish[] = { overworld_ascending_frames(sRhPg2_Fish, 4, 4) };
static const struct SpriteFrameImage sRhPg2_PicItem[] = { overworld_ascending_frames(sRhPg2_Item, 2, 4) };
static const struct SpriteFrameImage sRhPg2_PicItemBike[] = { overworld_ascending_frames(sRhPg2_ItemBike, 4, 4) };

static const u16 sRhPg3_Normal[] = INCGFX_U16("graphics/rh_player/leaf/normal.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg3_Surf[] = INCGFX_U16("graphics/rh_player/leaf/surf.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg3_Bike[] = INCGFX_U16("graphics/rh_player/leaf/bike.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg3_Fish[] = INCGFX_U16("graphics/rh_player/leaf/fish.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg3_Item[] = INCGFX_U16("graphics/rh_player/leaf/item.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg3_ItemBike[] = INCGFX_U16("graphics/rh_player/leaf/itembike.png", ".4bpp", "-mwidth 4 -mheight 4");
const u16 gRhPlayerPal3[] = INCGFX_U16("graphics/rh_player/leaf/normal.png", ".gbapal");
static const u32 sRhPg3_Front[] = INCGFX_U32("graphics/rh_player/leaf/front.png", ".4bpp.smol");
static const u16 sRhPg3_FrontPal[] = INCGFX_U16("graphics/rh_player/leaf/front.png", ".gbapal");
static const u32 sRhPg3_Oak[] = INCGFX_U32("graphics/rh_player/leaf/oak.png", ".8bpp.smol");
static const u8 sRhPg3_Back[] = INCGFX_U8("graphics/rh_player/leaf/back.png", ".4bpp");
static const u16 sRhPg3_BackPal[] = INCGFX_U16("graphics/rh_player/leaf/back.png", ".gbapal");
static const struct SpriteFrameImage sRhPg3_PicNormal[] = {
    overworld_frame(sRhPg3_Normal, 2, 4, 0),
    overworld_frame(sRhPg3_Normal, 2, 4, 1),
    overworld_frame(sRhPg3_Normal, 2, 4, 2),
    overworld_frame(sRhPg3_Normal, 2, 4, 3),
    overworld_frame(sRhPg3_Normal, 2, 4, 4),
    overworld_frame(sRhPg3_Normal, 2, 4, 5),
    overworld_frame(sRhPg3_Normal, 2, 4, 6),
    overworld_frame(sRhPg3_Normal, 2, 4, 7),
    overworld_frame(sRhPg3_Normal, 2, 4, 8),
    overworld_frame(sRhPg3_Normal, 2, 4, 9),
    overworld_frame(sRhPg3_Normal, 2, 4, 10),
    overworld_frame(sRhPg3_Normal, 2, 4, 11),
    overworld_frame(sRhPg3_Normal, 2, 4, 12),
    overworld_frame(sRhPg3_Normal, 2, 4, 13),
    overworld_frame(sRhPg3_Normal, 2, 4, 14),
    overworld_frame(sRhPg3_Normal, 2, 4, 15),
    overworld_frame(sRhPg3_Normal, 2, 4, 16),
    overworld_frame(sRhPg3_Normal, 2, 4, 17),
    overworld_frame(sRhPg3_Normal, 2, 4, 18),
    overworld_frame(sRhPg3_Normal, 2, 4, 19),
};
static const struct SpriteFrameImage sRhPg3_PicSurf[] = {
    overworld_frame(sRhPg3_Surf, 2, 4, 0),
    overworld_frame(sRhPg3_Surf, 2, 4, 1),
    overworld_frame(sRhPg3_Surf, 2, 4, 2),
    overworld_frame(sRhPg3_Surf, 2, 4, 0),
    overworld_frame(sRhPg3_Surf, 2, 4, 0),
    overworld_frame(sRhPg3_Surf, 2, 4, 1),
    overworld_frame(sRhPg3_Surf, 2, 4, 1),
    overworld_frame(sRhPg3_Surf, 2, 4, 2),
    overworld_frame(sRhPg3_Surf, 2, 4, 2),
    overworld_frame(sRhPg3_Surf, 2, 4, 0),
    overworld_frame(sRhPg3_Surf, 2, 4, 1),
    overworld_frame(sRhPg3_Surf, 2, 4, 2),
};
static const struct SpriteFrameImage sRhPg3_PicBike[] = { overworld_ascending_frames(sRhPg3_Bike, 4, 4) };
static const struct SpriteFrameImage sRhPg3_PicFish[] = { overworld_ascending_frames(sRhPg3_Fish, 4, 4) };
static const struct SpriteFrameImage sRhPg3_PicItem[] = { overworld_ascending_frames(sRhPg3_Item, 2, 4) };
static const struct SpriteFrameImage sRhPg3_PicItemBike[] = { overworld_ascending_frames(sRhPg3_ItemBike, 4, 4) };

static const u16 sRhPg4_Normal[] = INCGFX_U16("graphics/rh_player/brendan_e/normal.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg4_Surf[] = INCGFX_U16("graphics/rh_player/brendan_e/surf.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg4_Bike[] = INCGFX_U16("graphics/rh_player/brendan_e/bike.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg4_Fish[] = INCGFX_U16("graphics/rh_player/brendan_e/fish.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg4_Item[] = INCGFX_U16("graphics/rh_player/brendan_e/item.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg4_ItemBike[] = INCGFX_U16("graphics/rh_player/brendan_e/itembike.png", ".4bpp", "-mwidth 4 -mheight 4");
const u16 gRhPlayerPal4[] = INCGFX_U16("graphics/rh_player/brendan_e/normal.png", ".gbapal");
static const u32 sRhPg4_Front[] = INCGFX_U32("graphics/rh_player/brendan_e/front.png", ".4bpp.smol");
static const u16 sRhPg4_FrontPal[] = INCGFX_U16("graphics/rh_player/brendan_e/front.png", ".gbapal");
static const u32 sRhPg4_Oak[] = INCGFX_U32("graphics/rh_player/brendan_e/oak.png", ".8bpp.smol");
static const u8 sRhPg4_Back[] = INCGFX_U8("graphics/rh_player/brendan_e/back.png", ".4bpp");
static const u16 sRhPg4_BackPal[] = INCGFX_U16("graphics/rh_player/brendan_e/back.png", ".gbapal");
static const struct SpriteFrameImage sRhPg4_PicNormal[] = {
    overworld_frame(sRhPg4_Normal, 2, 4, 0),
    overworld_frame(sRhPg4_Normal, 2, 4, 1),
    overworld_frame(sRhPg4_Normal, 2, 4, 2),
    overworld_frame(sRhPg4_Normal, 2, 4, 3),
    overworld_frame(sRhPg4_Normal, 2, 4, 4),
    overworld_frame(sRhPg4_Normal, 2, 4, 5),
    overworld_frame(sRhPg4_Normal, 2, 4, 6),
    overworld_frame(sRhPg4_Normal, 2, 4, 7),
    overworld_frame(sRhPg4_Normal, 2, 4, 8),
    overworld_frame(sRhPg4_Normal, 2, 4, 9),
    overworld_frame(sRhPg4_Normal, 2, 4, 10),
    overworld_frame(sRhPg4_Normal, 2, 4, 11),
    overworld_frame(sRhPg4_Normal, 2, 4, 12),
    overworld_frame(sRhPg4_Normal, 2, 4, 13),
    overworld_frame(sRhPg4_Normal, 2, 4, 14),
    overworld_frame(sRhPg4_Normal, 2, 4, 15),
    overworld_frame(sRhPg4_Normal, 2, 4, 16),
    overworld_frame(sRhPg4_Normal, 2, 4, 17),
    overworld_frame(sRhPg4_Normal, 2, 4, 18),
    overworld_frame(sRhPg4_Normal, 2, 4, 19),
};
static const struct SpriteFrameImage sRhPg4_PicSurf[] = {
    overworld_frame(sRhPg4_Surf, 2, 4, 0),
    overworld_frame(sRhPg4_Surf, 2, 4, 1),
    overworld_frame(sRhPg4_Surf, 2, 4, 2),
    overworld_frame(sRhPg4_Surf, 2, 4, 0),
    overworld_frame(sRhPg4_Surf, 2, 4, 0),
    overworld_frame(sRhPg4_Surf, 2, 4, 1),
    overworld_frame(sRhPg4_Surf, 2, 4, 1),
    overworld_frame(sRhPg4_Surf, 2, 4, 2),
    overworld_frame(sRhPg4_Surf, 2, 4, 2),
    overworld_frame(sRhPg4_Surf, 2, 4, 0),
    overworld_frame(sRhPg4_Surf, 2, 4, 1),
    overworld_frame(sRhPg4_Surf, 2, 4, 2),
};
static const struct SpriteFrameImage sRhPg4_PicBike[] = { overworld_ascending_frames(sRhPg4_Bike, 4, 4) };
static const struct SpriteFrameImage sRhPg4_PicFish[] = { overworld_ascending_frames(sRhPg4_Fish, 4, 4) };
static const struct SpriteFrameImage sRhPg4_PicItem[] = { overworld_ascending_frames(sRhPg4_Item, 2, 4) };
static const struct SpriteFrameImage sRhPg4_PicItemBike[] = { overworld_ascending_frames(sRhPg4_ItemBike, 4, 4) };

static const u16 sRhPg5_Normal[] = INCGFX_U16("graphics/rh_player/may_e/normal.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg5_Surf[] = INCGFX_U16("graphics/rh_player/may_e/surf.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg5_Bike[] = INCGFX_U16("graphics/rh_player/may_e/bike.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg5_Fish[] = INCGFX_U16("graphics/rh_player/may_e/fish.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg5_Item[] = INCGFX_U16("graphics/rh_player/may_e/item.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg5_ItemBike[] = INCGFX_U16("graphics/rh_player/may_e/itembike.png", ".4bpp", "-mwidth 4 -mheight 4");
const u16 gRhPlayerPal5[] = INCGFX_U16("graphics/rh_player/may_e/normal.png", ".gbapal");
static const u32 sRhPg5_Front[] = INCGFX_U32("graphics/rh_player/may_e/front.png", ".4bpp.smol");
static const u16 sRhPg5_FrontPal[] = INCGFX_U16("graphics/rh_player/may_e/front.png", ".gbapal");
static const u32 sRhPg5_Oak[] = INCGFX_U32("graphics/rh_player/may_e/oak.png", ".8bpp.smol");
static const u8 sRhPg5_Back[] = INCGFX_U8("graphics/rh_player/may_e/back.png", ".4bpp");
static const u16 sRhPg5_BackPal[] = INCGFX_U16("graphics/rh_player/may_e/back.png", ".gbapal");
static const struct SpriteFrameImage sRhPg5_PicNormal[] = {
    overworld_frame(sRhPg5_Normal, 2, 4, 0),
    overworld_frame(sRhPg5_Normal, 2, 4, 1),
    overworld_frame(sRhPg5_Normal, 2, 4, 2),
    overworld_frame(sRhPg5_Normal, 2, 4, 3),
    overworld_frame(sRhPg5_Normal, 2, 4, 4),
    overworld_frame(sRhPg5_Normal, 2, 4, 5),
    overworld_frame(sRhPg5_Normal, 2, 4, 6),
    overworld_frame(sRhPg5_Normal, 2, 4, 7),
    overworld_frame(sRhPg5_Normal, 2, 4, 8),
    overworld_frame(sRhPg5_Normal, 2, 4, 9),
    overworld_frame(sRhPg5_Normal, 2, 4, 10),
    overworld_frame(sRhPg5_Normal, 2, 4, 11),
    overworld_frame(sRhPg5_Normal, 2, 4, 12),
    overworld_frame(sRhPg5_Normal, 2, 4, 13),
    overworld_frame(sRhPg5_Normal, 2, 4, 14),
    overworld_frame(sRhPg5_Normal, 2, 4, 15),
    overworld_frame(sRhPg5_Normal, 2, 4, 16),
    overworld_frame(sRhPg5_Normal, 2, 4, 17),
    overworld_frame(sRhPg5_Normal, 2, 4, 18),
    overworld_frame(sRhPg5_Normal, 2, 4, 19),
};
static const struct SpriteFrameImage sRhPg5_PicSurf[] = {
    overworld_frame(sRhPg5_Surf, 2, 4, 0),
    overworld_frame(sRhPg5_Surf, 2, 4, 1),
    overworld_frame(sRhPg5_Surf, 2, 4, 2),
    overworld_frame(sRhPg5_Surf, 2, 4, 0),
    overworld_frame(sRhPg5_Surf, 2, 4, 0),
    overworld_frame(sRhPg5_Surf, 2, 4, 1),
    overworld_frame(sRhPg5_Surf, 2, 4, 1),
    overworld_frame(sRhPg5_Surf, 2, 4, 2),
    overworld_frame(sRhPg5_Surf, 2, 4, 2),
    overworld_frame(sRhPg5_Surf, 2, 4, 0),
    overworld_frame(sRhPg5_Surf, 2, 4, 1),
    overworld_frame(sRhPg5_Surf, 2, 4, 2),
};
static const struct SpriteFrameImage sRhPg5_PicBike[] = { overworld_ascending_frames(sRhPg5_Bike, 4, 4) };
static const struct SpriteFrameImage sRhPg5_PicFish[] = { overworld_ascending_frames(sRhPg5_Fish, 4, 4) };
static const struct SpriteFrameImage sRhPg5_PicItem[] = { overworld_ascending_frames(sRhPg5_Item, 2, 4) };
static const struct SpriteFrameImage sRhPg5_PicItemBike[] = { overworld_ascending_frames(sRhPg5_ItemBike, 4, 4) };

static const u16 sRhPg6_Normal[] = INCGFX_U16("graphics/rh_player/brendan_rs/normal.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg6_Surf[] = INCGFX_U16("graphics/rh_player/brendan_rs/surf.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg6_Bike[] = INCGFX_U16("graphics/rh_player/brendan_rs/bike.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg6_Fish[] = INCGFX_U16("graphics/rh_player/brendan_rs/fish.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg6_Item[] = INCGFX_U16("graphics/rh_player/brendan_rs/item.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg6_ItemBike[] = INCGFX_U16("graphics/rh_player/brendan_rs/itembike.png", ".4bpp", "-mwidth 4 -mheight 4");
const u16 gRhPlayerPal6[] = INCGFX_U16("graphics/rh_player/brendan_rs/normal.png", ".gbapal");
static const u32 sRhPg6_Front[] = INCGFX_U32("graphics/rh_player/brendan_rs/front.png", ".4bpp.smol");
static const u16 sRhPg6_FrontPal[] = INCGFX_U16("graphics/rh_player/brendan_rs/front.png", ".gbapal");
static const u32 sRhPg6_Oak[] = INCGFX_U32("graphics/rh_player/brendan_rs/oak.png", ".8bpp.smol");
static const u8 sRhPg6_Back[] = INCGFX_U8("graphics/rh_player/brendan_rs/back.png", ".4bpp");
static const u16 sRhPg6_BackPal[] = INCGFX_U16("graphics/rh_player/brendan_rs/back.png", ".gbapal");
static const struct SpriteFrameImage sRhPg6_PicNormal[] = {
    overworld_frame(sRhPg6_Normal, 2, 4, 0),
    overworld_frame(sRhPg6_Normal, 2, 4, 1),
    overworld_frame(sRhPg6_Normal, 2, 4, 2),
    overworld_frame(sRhPg6_Normal, 2, 4, 3),
    overworld_frame(sRhPg6_Normal, 2, 4, 4),
    overworld_frame(sRhPg6_Normal, 2, 4, 5),
    overworld_frame(sRhPg6_Normal, 2, 4, 6),
    overworld_frame(sRhPg6_Normal, 2, 4, 7),
    overworld_frame(sRhPg6_Normal, 2, 4, 8),
    overworld_frame(sRhPg6_Normal, 2, 4, 9),
    overworld_frame(sRhPg6_Normal, 2, 4, 10),
    overworld_frame(sRhPg6_Normal, 2, 4, 11),
    overworld_frame(sRhPg6_Normal, 2, 4, 12),
    overworld_frame(sRhPg6_Normal, 2, 4, 13),
    overworld_frame(sRhPg6_Normal, 2, 4, 14),
    overworld_frame(sRhPg6_Normal, 2, 4, 15),
    overworld_frame(sRhPg6_Normal, 2, 4, 16),
    overworld_frame(sRhPg6_Normal, 2, 4, 17),
    overworld_frame(sRhPg6_Normal, 2, 4, 18),
    overworld_frame(sRhPg6_Normal, 2, 4, 19),
};
static const struct SpriteFrameImage sRhPg6_PicSurf[] = {
    overworld_frame(sRhPg6_Surf, 2, 4, 0),
    overworld_frame(sRhPg6_Surf, 2, 4, 1),
    overworld_frame(sRhPg6_Surf, 2, 4, 2),
    overworld_frame(sRhPg6_Surf, 2, 4, 0),
    overworld_frame(sRhPg6_Surf, 2, 4, 0),
    overworld_frame(sRhPg6_Surf, 2, 4, 1),
    overworld_frame(sRhPg6_Surf, 2, 4, 1),
    overworld_frame(sRhPg6_Surf, 2, 4, 2),
    overworld_frame(sRhPg6_Surf, 2, 4, 2),
    overworld_frame(sRhPg6_Surf, 2, 4, 0),
    overworld_frame(sRhPg6_Surf, 2, 4, 1),
    overworld_frame(sRhPg6_Surf, 2, 4, 2),
};
static const struct SpriteFrameImage sRhPg6_PicBike[] = { overworld_ascending_frames(sRhPg6_Bike, 4, 4) };
static const struct SpriteFrameImage sRhPg6_PicFish[] = { overworld_ascending_frames(sRhPg6_Fish, 4, 4) };
static const struct SpriteFrameImage sRhPg6_PicItem[] = { overworld_ascending_frames(sRhPg6_Item, 2, 4) };
static const struct SpriteFrameImage sRhPg6_PicItemBike[] = { overworld_ascending_frames(sRhPg6_ItemBike, 4, 4) };

static const u16 sRhPg7_Normal[] = INCGFX_U16("graphics/rh_player/may_rs/normal.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg7_Surf[] = INCGFX_U16("graphics/rh_player/may_rs/surf.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg7_Bike[] = INCGFX_U16("graphics/rh_player/may_rs/bike.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg7_Fish[] = INCGFX_U16("graphics/rh_player/may_rs/fish.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg7_Item[] = INCGFX_U16("graphics/rh_player/may_rs/item.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg7_ItemBike[] = INCGFX_U16("graphics/rh_player/may_rs/itembike.png", ".4bpp", "-mwidth 4 -mheight 4");
const u16 gRhPlayerPal7[] = INCGFX_U16("graphics/rh_player/may_rs/normal.png", ".gbapal");
static const u32 sRhPg7_Front[] = INCGFX_U32("graphics/rh_player/may_rs/front.png", ".4bpp.smol");
static const u16 sRhPg7_FrontPal[] = INCGFX_U16("graphics/rh_player/may_rs/front.png", ".gbapal");
static const u32 sRhPg7_Oak[] = INCGFX_U32("graphics/rh_player/may_rs/oak.png", ".8bpp.smol");
static const u8 sRhPg7_Back[] = INCGFX_U8("graphics/rh_player/may_rs/back.png", ".4bpp");
static const u16 sRhPg7_BackPal[] = INCGFX_U16("graphics/rh_player/may_rs/back.png", ".gbapal");
static const struct SpriteFrameImage sRhPg7_PicNormal[] = {
    overworld_frame(sRhPg7_Normal, 2, 4, 0),
    overworld_frame(sRhPg7_Normal, 2, 4, 1),
    overworld_frame(sRhPg7_Normal, 2, 4, 2),
    overworld_frame(sRhPg7_Normal, 2, 4, 3),
    overworld_frame(sRhPg7_Normal, 2, 4, 4),
    overworld_frame(sRhPg7_Normal, 2, 4, 5),
    overworld_frame(sRhPg7_Normal, 2, 4, 6),
    overworld_frame(sRhPg7_Normal, 2, 4, 7),
    overworld_frame(sRhPg7_Normal, 2, 4, 8),
    overworld_frame(sRhPg7_Normal, 2, 4, 9),
    overworld_frame(sRhPg7_Normal, 2, 4, 10),
    overworld_frame(sRhPg7_Normal, 2, 4, 11),
    overworld_frame(sRhPg7_Normal, 2, 4, 12),
    overworld_frame(sRhPg7_Normal, 2, 4, 13),
    overworld_frame(sRhPg7_Normal, 2, 4, 14),
    overworld_frame(sRhPg7_Normal, 2, 4, 15),
    overworld_frame(sRhPg7_Normal, 2, 4, 16),
    overworld_frame(sRhPg7_Normal, 2, 4, 17),
    overworld_frame(sRhPg7_Normal, 2, 4, 18),
    overworld_frame(sRhPg7_Normal, 2, 4, 19),
};
static const struct SpriteFrameImage sRhPg7_PicSurf[] = {
    overworld_frame(sRhPg7_Surf, 2, 4, 0),
    overworld_frame(sRhPg7_Surf, 2, 4, 1),
    overworld_frame(sRhPg7_Surf, 2, 4, 2),
    overworld_frame(sRhPg7_Surf, 2, 4, 0),
    overworld_frame(sRhPg7_Surf, 2, 4, 0),
    overworld_frame(sRhPg7_Surf, 2, 4, 1),
    overworld_frame(sRhPg7_Surf, 2, 4, 1),
    overworld_frame(sRhPg7_Surf, 2, 4, 2),
    overworld_frame(sRhPg7_Surf, 2, 4, 2),
    overworld_frame(sRhPg7_Surf, 2, 4, 0),
    overworld_frame(sRhPg7_Surf, 2, 4, 1),
    overworld_frame(sRhPg7_Surf, 2, 4, 2),
};
static const struct SpriteFrameImage sRhPg7_PicBike[] = { overworld_ascending_frames(sRhPg7_Bike, 4, 4) };
static const struct SpriteFrameImage sRhPg7_PicFish[] = { overworld_ascending_frames(sRhPg7_Fish, 4, 4) };
static const struct SpriteFrameImage sRhPg7_PicItem[] = { overworld_ascending_frames(sRhPg7_Item, 2, 4) };
static const struct SpriteFrameImage sRhPg7_PicItemBike[] = { overworld_ascending_frames(sRhPg7_ItemBike, 4, 4) };

static const u16 sRhPg8_Normal[] = INCGFX_U16("graphics/rh_player/wally/normal.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg8_Surf[] = INCGFX_U16("graphics/rh_player/wally/surf.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg8_Bike[] = INCGFX_U16("graphics/rh_player/wally/bike.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg8_Fish[] = INCGFX_U16("graphics/rh_player/wally/fish.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg8_Item[] = INCGFX_U16("graphics/rh_player/wally/item.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg8_ItemBike[] = INCGFX_U16("graphics/rh_player/wally/itembike.png", ".4bpp", "-mwidth 4 -mheight 4");
const u16 gRhPlayerPal8[] = INCGFX_U16("graphics/rh_player/wally/normal.png", ".gbapal");
static const u32 sRhPg8_Front[] = INCGFX_U32("graphics/rh_player/wally/front.png", ".4bpp.smol");
static const u16 sRhPg8_FrontPal[] = INCGFX_U16("graphics/rh_player/wally/front.png", ".gbapal");
static const u32 sRhPg8_Oak[] = INCGFX_U32("graphics/rh_player/wally/oak.png", ".8bpp.smol");
static const u8 sRhPg8_Back[] = INCGFX_U8("graphics/rh_player/wally/back.png", ".4bpp");
static const u16 sRhPg8_BackPal[] = INCGFX_U16("graphics/rh_player/wally/back.png", ".gbapal");
static const struct SpriteFrameImage sRhPg8_PicNormal[] = {
    overworld_frame(sRhPg8_Normal, 2, 4, 0),
    overworld_frame(sRhPg8_Normal, 2, 4, 1),
    overworld_frame(sRhPg8_Normal, 2, 4, 2),
    overworld_frame(sRhPg8_Normal, 2, 4, 3),
    overworld_frame(sRhPg8_Normal, 2, 4, 4),
    overworld_frame(sRhPg8_Normal, 2, 4, 5),
    overworld_frame(sRhPg8_Normal, 2, 4, 6),
    overworld_frame(sRhPg8_Normal, 2, 4, 7),
    overworld_frame(sRhPg8_Normal, 2, 4, 8),
    overworld_frame(sRhPg8_Normal, 2, 4, 9),
    overworld_frame(sRhPg8_Normal, 2, 4, 10),
    overworld_frame(sRhPg8_Normal, 2, 4, 11),
    overworld_frame(sRhPg8_Normal, 2, 4, 12),
    overworld_frame(sRhPg8_Normal, 2, 4, 13),
    overworld_frame(sRhPg8_Normal, 2, 4, 14),
    overworld_frame(sRhPg8_Normal, 2, 4, 15),
    overworld_frame(sRhPg8_Normal, 2, 4, 16),
    overworld_frame(sRhPg8_Normal, 2, 4, 17),
    overworld_frame(sRhPg8_Normal, 2, 4, 18),
    overworld_frame(sRhPg8_Normal, 2, 4, 19),
};
static const struct SpriteFrameImage sRhPg8_PicSurf[] = {
    overworld_frame(sRhPg8_Surf, 2, 4, 0),
    overworld_frame(sRhPg8_Surf, 2, 4, 1),
    overworld_frame(sRhPg8_Surf, 2, 4, 2),
    overworld_frame(sRhPg8_Surf, 2, 4, 0),
    overworld_frame(sRhPg8_Surf, 2, 4, 0),
    overworld_frame(sRhPg8_Surf, 2, 4, 1),
    overworld_frame(sRhPg8_Surf, 2, 4, 1),
    overworld_frame(sRhPg8_Surf, 2, 4, 2),
    overworld_frame(sRhPg8_Surf, 2, 4, 2),
    overworld_frame(sRhPg8_Surf, 2, 4, 0),
    overworld_frame(sRhPg8_Surf, 2, 4, 1),
    overworld_frame(sRhPg8_Surf, 2, 4, 2),
};
static const struct SpriteFrameImage sRhPg8_PicBike[] = { overworld_ascending_frames(sRhPg8_Bike, 4, 4) };
static const struct SpriteFrameImage sRhPg8_PicFish[] = { overworld_ascending_frames(sRhPg8_Fish, 4, 4) };
static const struct SpriteFrameImage sRhPg8_PicItem[] = { overworld_ascending_frames(sRhPg8_Item, 2, 4) };
static const struct SpriteFrameImage sRhPg8_PicItemBike[] = { overworld_ascending_frames(sRhPg8_ItemBike, 4, 4) };

static const u16 sRhPg9_Normal[] = INCGFX_U16("graphics/rh_player/prof_birch/normal.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg9_Surf[] = INCGFX_U16("graphics/rh_player/prof_birch/surf.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg9_Bike[] = INCGFX_U16("graphics/rh_player/prof_birch/bike.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg9_Fish[] = INCGFX_U16("graphics/rh_player/prof_birch/fish.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg9_Item[] = INCGFX_U16("graphics/rh_player/prof_birch/item.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg9_ItemBike[] = INCGFX_U16("graphics/rh_player/prof_birch/itembike.png", ".4bpp", "-mwidth 4 -mheight 4");
const u16 gRhPlayerPal9[] = INCGFX_U16("graphics/rh_player/prof_birch/normal.png", ".gbapal");
static const u32 sRhPg9_Front[] = INCGFX_U32("graphics/rh_player/prof_birch/front.png", ".4bpp.smol");
static const u16 sRhPg9_FrontPal[] = INCGFX_U16("graphics/rh_player/prof_birch/front.png", ".gbapal");
static const u32 sRhPg9_Oak[] = INCGFX_U32("graphics/rh_player/prof_birch/oak.png", ".8bpp.smol");
static const u8 sRhPg9_Back[] = INCGFX_U8("graphics/rh_player/prof_birch/back.png", ".4bpp");
static const u16 sRhPg9_BackPal[] = INCGFX_U16("graphics/rh_player/prof_birch/back.png", ".gbapal");
static const struct SpriteFrameImage sRhPg9_PicNormal[] = {
    overworld_frame(sRhPg9_Normal, 2, 4, 0),
    overworld_frame(sRhPg9_Normal, 2, 4, 1),
    overworld_frame(sRhPg9_Normal, 2, 4, 2),
    overworld_frame(sRhPg9_Normal, 2, 4, 3),
    overworld_frame(sRhPg9_Normal, 2, 4, 4),
    overworld_frame(sRhPg9_Normal, 2, 4, 5),
    overworld_frame(sRhPg9_Normal, 2, 4, 6),
    overworld_frame(sRhPg9_Normal, 2, 4, 7),
    overworld_frame(sRhPg9_Normal, 2, 4, 8),
    overworld_frame(sRhPg9_Normal, 2, 4, 9),
    overworld_frame(sRhPg9_Normal, 2, 4, 10),
    overworld_frame(sRhPg9_Normal, 2, 4, 11),
    overworld_frame(sRhPg9_Normal, 2, 4, 12),
    overworld_frame(sRhPg9_Normal, 2, 4, 13),
    overworld_frame(sRhPg9_Normal, 2, 4, 14),
    overworld_frame(sRhPg9_Normal, 2, 4, 15),
    overworld_frame(sRhPg9_Normal, 2, 4, 16),
    overworld_frame(sRhPg9_Normal, 2, 4, 17),
    overworld_frame(sRhPg9_Normal, 2, 4, 18),
    overworld_frame(sRhPg9_Normal, 2, 4, 19),
};
static const struct SpriteFrameImage sRhPg9_PicSurf[] = {
    overworld_frame(sRhPg9_Surf, 2, 4, 0),
    overworld_frame(sRhPg9_Surf, 2, 4, 1),
    overworld_frame(sRhPg9_Surf, 2, 4, 2),
    overworld_frame(sRhPg9_Surf, 2, 4, 0),
    overworld_frame(sRhPg9_Surf, 2, 4, 0),
    overworld_frame(sRhPg9_Surf, 2, 4, 1),
    overworld_frame(sRhPg9_Surf, 2, 4, 1),
    overworld_frame(sRhPg9_Surf, 2, 4, 2),
    overworld_frame(sRhPg9_Surf, 2, 4, 2),
    overworld_frame(sRhPg9_Surf, 2, 4, 0),
    overworld_frame(sRhPg9_Surf, 2, 4, 1),
    overworld_frame(sRhPg9_Surf, 2, 4, 2),
};
static const struct SpriteFrameImage sRhPg9_PicBike[] = { overworld_ascending_frames(sRhPg9_Bike, 4, 4) };
static const struct SpriteFrameImage sRhPg9_PicFish[] = { overworld_ascending_frames(sRhPg9_Fish, 4, 4) };
static const struct SpriteFrameImage sRhPg9_PicItem[] = { overworld_ascending_frames(sRhPg9_Item, 2, 4) };
static const struct SpriteFrameImage sRhPg9_PicItemBike[] = { overworld_ascending_frames(sRhPg9_ItemBike, 4, 4) };

static const u16 sRhPg10_Normal[] = INCGFX_U16("graphics/rh_player/cynthia/normal.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg10_Surf[] = INCGFX_U16("graphics/rh_player/cynthia/surf.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg10_Bike[] = INCGFX_U16("graphics/rh_player/cynthia/bike.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg10_Fish[] = INCGFX_U16("graphics/rh_player/cynthia/fish.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg10_Item[] = INCGFX_U16("graphics/rh_player/cynthia/item.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg10_ItemBike[] = INCGFX_U16("graphics/rh_player/cynthia/itembike.png", ".4bpp", "-mwidth 4 -mheight 4");
const u16 gRhPlayerPal10[] = INCGFX_U16("graphics/rh_player/cynthia/normal.png", ".gbapal");
static const u32 sRhPg10_Front[] = INCGFX_U32("graphics/rh_player/cynthia/front.png", ".4bpp.smol");
static const u16 sRhPg10_FrontPal[] = INCGFX_U16("graphics/rh_player/cynthia/front.png", ".gbapal");
static const u32 sRhPg10_Oak[] = INCGFX_U32("graphics/rh_player/cynthia/oak.png", ".8bpp.smol");
static const u8 sRhPg10_Back[] = INCGFX_U8("graphics/rh_player/cynthia/back.png", ".4bpp");
static const u16 sRhPg10_BackPal[] = INCGFX_U16("graphics/rh_player/cynthia/back.png", ".gbapal");
static const struct SpriteFrameImage sRhPg10_PicNormal[] = {
    overworld_frame(sRhPg10_Normal, 2, 4, 0),
    overworld_frame(sRhPg10_Normal, 2, 4, 1),
    overworld_frame(sRhPg10_Normal, 2, 4, 2),
    overworld_frame(sRhPg10_Normal, 2, 4, 3),
    overworld_frame(sRhPg10_Normal, 2, 4, 4),
    overworld_frame(sRhPg10_Normal, 2, 4, 5),
    overworld_frame(sRhPg10_Normal, 2, 4, 6),
    overworld_frame(sRhPg10_Normal, 2, 4, 7),
    overworld_frame(sRhPg10_Normal, 2, 4, 8),
    overworld_frame(sRhPg10_Normal, 2, 4, 9),
    overworld_frame(sRhPg10_Normal, 2, 4, 10),
    overworld_frame(sRhPg10_Normal, 2, 4, 11),
    overworld_frame(sRhPg10_Normal, 2, 4, 12),
    overworld_frame(sRhPg10_Normal, 2, 4, 13),
    overworld_frame(sRhPg10_Normal, 2, 4, 14),
    overworld_frame(sRhPg10_Normal, 2, 4, 15),
    overworld_frame(sRhPg10_Normal, 2, 4, 16),
    overworld_frame(sRhPg10_Normal, 2, 4, 17),
    overworld_frame(sRhPg10_Normal, 2, 4, 18),
    overworld_frame(sRhPg10_Normal, 2, 4, 19),
};
static const struct SpriteFrameImage sRhPg10_PicSurf[] = {
    overworld_frame(sRhPg10_Surf, 2, 4, 0),
    overworld_frame(sRhPg10_Surf, 2, 4, 1),
    overworld_frame(sRhPg10_Surf, 2, 4, 2),
    overworld_frame(sRhPg10_Surf, 2, 4, 0),
    overworld_frame(sRhPg10_Surf, 2, 4, 0),
    overworld_frame(sRhPg10_Surf, 2, 4, 1),
    overworld_frame(sRhPg10_Surf, 2, 4, 1),
    overworld_frame(sRhPg10_Surf, 2, 4, 2),
    overworld_frame(sRhPg10_Surf, 2, 4, 2),
    overworld_frame(sRhPg10_Surf, 2, 4, 0),
    overworld_frame(sRhPg10_Surf, 2, 4, 1),
    overworld_frame(sRhPg10_Surf, 2, 4, 2),
};
static const struct SpriteFrameImage sRhPg10_PicBike[] = { overworld_ascending_frames(sRhPg10_Bike, 4, 4) };
static const struct SpriteFrameImage sRhPg10_PicFish[] = { overworld_ascending_frames(sRhPg10_Fish, 4, 4) };
static const struct SpriteFrameImage sRhPg10_PicItem[] = { overworld_ascending_frames(sRhPg10_Item, 2, 4) };
static const struct SpriteFrameImage sRhPg10_PicItemBike[] = { overworld_ascending_frames(sRhPg10_ItemBike, 4, 4) };

static const u16 sRhPg11_Normal[] = INCGFX_U16("graphics/rh_player/ghost/normal.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg11_Surf[] = INCGFX_U16("graphics/rh_player/ghost/surf.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg11_Bike[] = INCGFX_U16("graphics/rh_player/ghost/bike.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg11_Fish[] = INCGFX_U16("graphics/rh_player/ghost/fish.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg11_Item[] = INCGFX_U16("graphics/rh_player/ghost/item.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg11_ItemBike[] = INCGFX_U16("graphics/rh_player/ghost/itembike.png", ".4bpp", "-mwidth 4 -mheight 4");
const u16 gRhPlayerPal11[] = INCGFX_U16("graphics/rh_player/ghost/normal.png", ".gbapal");
static const u32 sRhPg11_Front[] = INCGFX_U32("graphics/rh_player/ghost/front.png", ".4bpp.smol");
static const u16 sRhPg11_FrontPal[] = INCGFX_U16("graphics/rh_player/ghost/front.png", ".gbapal");
static const u32 sRhPg11_Oak[] = INCGFX_U32("graphics/rh_player/ghost/oak.png", ".8bpp.smol");
static const u8 sRhPg11_Back[] = INCGFX_U8("graphics/rh_player/ghost/back.png", ".4bpp");
static const u16 sRhPg11_BackPal[] = INCGFX_U16("graphics/rh_player/ghost/back.png", ".gbapal");
static const struct SpriteFrameImage sRhPg11_PicNormal[] = {
    overworld_frame(sRhPg11_Normal, 2, 4, 0),
    overworld_frame(sRhPg11_Normal, 2, 4, 1),
    overworld_frame(sRhPg11_Normal, 2, 4, 2),
    overworld_frame(sRhPg11_Normal, 2, 4, 3),
    overworld_frame(sRhPg11_Normal, 2, 4, 4),
    overworld_frame(sRhPg11_Normal, 2, 4, 5),
    overworld_frame(sRhPg11_Normal, 2, 4, 6),
    overworld_frame(sRhPg11_Normal, 2, 4, 7),
    overworld_frame(sRhPg11_Normal, 2, 4, 8),
    overworld_frame(sRhPg11_Normal, 2, 4, 9),
    overworld_frame(sRhPg11_Normal, 2, 4, 10),
    overworld_frame(sRhPg11_Normal, 2, 4, 11),
    overworld_frame(sRhPg11_Normal, 2, 4, 12),
    overworld_frame(sRhPg11_Normal, 2, 4, 13),
    overworld_frame(sRhPg11_Normal, 2, 4, 14),
    overworld_frame(sRhPg11_Normal, 2, 4, 15),
    overworld_frame(sRhPg11_Normal, 2, 4, 16),
    overworld_frame(sRhPg11_Normal, 2, 4, 17),
    overworld_frame(sRhPg11_Normal, 2, 4, 18),
    overworld_frame(sRhPg11_Normal, 2, 4, 19),
};
static const struct SpriteFrameImage sRhPg11_PicSurf[] = {
    overworld_frame(sRhPg11_Surf, 2, 4, 0),
    overworld_frame(sRhPg11_Surf, 2, 4, 1),
    overworld_frame(sRhPg11_Surf, 2, 4, 2),
    overworld_frame(sRhPg11_Surf, 2, 4, 0),
    overworld_frame(sRhPg11_Surf, 2, 4, 0),
    overworld_frame(sRhPg11_Surf, 2, 4, 1),
    overworld_frame(sRhPg11_Surf, 2, 4, 1),
    overworld_frame(sRhPg11_Surf, 2, 4, 2),
    overworld_frame(sRhPg11_Surf, 2, 4, 2),
    overworld_frame(sRhPg11_Surf, 2, 4, 0),
    overworld_frame(sRhPg11_Surf, 2, 4, 1),
    overworld_frame(sRhPg11_Surf, 2, 4, 2),
};
static const struct SpriteFrameImage sRhPg11_PicBike[] = { overworld_ascending_frames(sRhPg11_Bike, 4, 4) };
static const struct SpriteFrameImage sRhPg11_PicFish[] = { overworld_ascending_frames(sRhPg11_Fish, 4, 4) };
static const struct SpriteFrameImage sRhPg11_PicItem[] = { overworld_ascending_frames(sRhPg11_Item, 2, 4) };
static const struct SpriteFrameImage sRhPg11_PicItemBike[] = { overworld_ascending_frames(sRhPg11_ItemBike, 4, 4) };

static const u16 sRhPg12_Normal[] = INCGFX_U16("graphics/rh_player/wraith/normal.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg12_Surf[] = INCGFX_U16("graphics/rh_player/wraith/surf.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg12_Bike[] = INCGFX_U16("graphics/rh_player/wraith/bike.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg12_Fish[] = INCGFX_U16("graphics/rh_player/wraith/fish.png", ".4bpp", "-mwidth 4 -mheight 4");
static const u16 sRhPg12_Item[] = INCGFX_U16("graphics/rh_player/wraith/item.png", ".4bpp", "-mwidth 2 -mheight 4");
static const u16 sRhPg12_ItemBike[] = INCGFX_U16("graphics/rh_player/wraith/itembike.png", ".4bpp", "-mwidth 4 -mheight 4");
const u16 gRhPlayerPal12[] = INCGFX_U16("graphics/rh_player/wraith/normal.png", ".gbapal");
static const u32 sRhPg12_Front[] = INCGFX_U32("graphics/rh_player/wraith/front.png", ".4bpp.smol");
static const u16 sRhPg12_FrontPal[] = INCGFX_U16("graphics/rh_player/wraith/front.png", ".gbapal");
static const u32 sRhPg12_Oak[] = INCGFX_U32("graphics/rh_player/wraith/oak.png", ".8bpp.smol");
static const u8 sRhPg12_Back[] = INCGFX_U8("graphics/rh_player/wraith/back.png", ".4bpp");
static const u16 sRhPg12_BackPal[] = INCGFX_U16("graphics/rh_player/wraith/back.png", ".gbapal");
static const struct SpriteFrameImage sRhPg12_PicNormal[] = {
    overworld_frame(sRhPg12_Normal, 2, 4, 0),
    overworld_frame(sRhPg12_Normal, 2, 4, 1),
    overworld_frame(sRhPg12_Normal, 2, 4, 2),
    overworld_frame(sRhPg12_Normal, 2, 4, 3),
    overworld_frame(sRhPg12_Normal, 2, 4, 4),
    overworld_frame(sRhPg12_Normal, 2, 4, 5),
    overworld_frame(sRhPg12_Normal, 2, 4, 6),
    overworld_frame(sRhPg12_Normal, 2, 4, 7),
    overworld_frame(sRhPg12_Normal, 2, 4, 8),
    overworld_frame(sRhPg12_Normal, 2, 4, 9),
    overworld_frame(sRhPg12_Normal, 2, 4, 10),
    overworld_frame(sRhPg12_Normal, 2, 4, 11),
    overworld_frame(sRhPg12_Normal, 2, 4, 12),
    overworld_frame(sRhPg12_Normal, 2, 4, 13),
    overworld_frame(sRhPg12_Normal, 2, 4, 14),
    overworld_frame(sRhPg12_Normal, 2, 4, 15),
    overworld_frame(sRhPg12_Normal, 2, 4, 16),
    overworld_frame(sRhPg12_Normal, 2, 4, 17),
    overworld_frame(sRhPg12_Normal, 2, 4, 18),
    overworld_frame(sRhPg12_Normal, 2, 4, 19),
};
static const struct SpriteFrameImage sRhPg12_PicSurf[] = {
    overworld_frame(sRhPg12_Surf, 2, 4, 0),
    overworld_frame(sRhPg12_Surf, 2, 4, 1),
    overworld_frame(sRhPg12_Surf, 2, 4, 2),
    overworld_frame(sRhPg12_Surf, 2, 4, 0),
    overworld_frame(sRhPg12_Surf, 2, 4, 0),
    overworld_frame(sRhPg12_Surf, 2, 4, 1),
    overworld_frame(sRhPg12_Surf, 2, 4, 1),
    overworld_frame(sRhPg12_Surf, 2, 4, 2),
    overworld_frame(sRhPg12_Surf, 2, 4, 2),
    overworld_frame(sRhPg12_Surf, 2, 4, 0),
    overworld_frame(sRhPg12_Surf, 2, 4, 1),
    overworld_frame(sRhPg12_Surf, 2, 4, 2),
};
static const struct SpriteFrameImage sRhPg12_PicBike[] = { overworld_ascending_frames(sRhPg12_Bike, 4, 4) };
static const struct SpriteFrameImage sRhPg12_PicFish[] = { overworld_ascending_frames(sRhPg12_Fish, 4, 4) };
static const struct SpriteFrameImage sRhPg12_PicItem[] = { overworld_ascending_frames(sRhPg12_Item, 2, 4) };
static const struct SpriteFrameImage sRhPg12_PicItemBike[] = { overworld_ascending_frames(sRhPg12_ItemBike, 4, 4) };

static const struct RhPlayerPack sRhPlayerPacks[] = {
    { .normal = sRhPg0_PicNormal, .surf = sRhPg0_PicSurf, .bike = sRhPg0_PicBike, .fish = sRhPg0_PicFish, .item = sRhPg0_PicItem, .itemBike = sRhPg0_PicItemBike, .front = sRhPg0_Front, .frontPal = sRhPg0_FrontPal, .oak = sRhPg0_Oak, .back = sRhPg0_Back, .backPal = sRhPg0_BackPal },
    { .normal = sRhPg1_PicNormal, .surf = sRhPg1_PicSurf, .bike = sRhPg1_PicBike, .fish = sRhPg1_PicFish, .item = sRhPg1_PicItem, .itemBike = sRhPg1_PicItemBike, .front = sRhPg1_Front, .frontPal = sRhPg1_FrontPal, .oak = sRhPg1_Oak, .back = sRhPg1_Back, .backPal = sRhPg1_BackPal },
    { .normal = sRhPg2_PicNormal, .surf = sRhPg2_PicSurf, .bike = sRhPg2_PicBike, .fish = sRhPg2_PicFish, .item = sRhPg2_PicItem, .itemBike = sRhPg2_PicItemBike, .front = sRhPg2_Front, .frontPal = sRhPg2_FrontPal, .oak = sRhPg2_Oak, .back = sRhPg2_Back, .backPal = sRhPg2_BackPal },
    { .normal = sRhPg3_PicNormal, .surf = sRhPg3_PicSurf, .bike = sRhPg3_PicBike, .fish = sRhPg3_PicFish, .item = sRhPg3_PicItem, .itemBike = sRhPg3_PicItemBike, .front = sRhPg3_Front, .frontPal = sRhPg3_FrontPal, .oak = sRhPg3_Oak, .back = sRhPg3_Back, .backPal = sRhPg3_BackPal },
    { .normal = sRhPg4_PicNormal, .surf = sRhPg4_PicSurf, .bike = sRhPg4_PicBike, .fish = sRhPg4_PicFish, .item = sRhPg4_PicItem, .itemBike = sRhPg4_PicItemBike, .front = sRhPg4_Front, .frontPal = sRhPg4_FrontPal, .oak = sRhPg4_Oak, .back = sRhPg4_Back, .backPal = sRhPg4_BackPal },
    { .normal = sRhPg5_PicNormal, .surf = sRhPg5_PicSurf, .bike = sRhPg5_PicBike, .fish = sRhPg5_PicFish, .item = sRhPg5_PicItem, .itemBike = sRhPg5_PicItemBike, .front = sRhPg5_Front, .frontPal = sRhPg5_FrontPal, .oak = sRhPg5_Oak, .back = sRhPg5_Back, .backPal = sRhPg5_BackPal },
    { .normal = sRhPg6_PicNormal, .surf = sRhPg6_PicSurf, .bike = sRhPg6_PicBike, .fish = sRhPg6_PicFish, .item = sRhPg6_PicItem, .itemBike = sRhPg6_PicItemBike, .front = sRhPg6_Front, .frontPal = sRhPg6_FrontPal, .oak = sRhPg6_Oak, .back = sRhPg6_Back, .backPal = sRhPg6_BackPal },
    { .normal = sRhPg7_PicNormal, .surf = sRhPg7_PicSurf, .bike = sRhPg7_PicBike, .fish = sRhPg7_PicFish, .item = sRhPg7_PicItem, .itemBike = sRhPg7_PicItemBike, .front = sRhPg7_Front, .frontPal = sRhPg7_FrontPal, .oak = sRhPg7_Oak, .back = sRhPg7_Back, .backPal = sRhPg7_BackPal },
    { .normal = sRhPg8_PicNormal, .surf = sRhPg8_PicSurf, .bike = sRhPg8_PicBike, .fish = sRhPg8_PicFish, .item = sRhPg8_PicItem, .itemBike = sRhPg8_PicItemBike, .front = sRhPg8_Front, .frontPal = sRhPg8_FrontPal, .oak = sRhPg8_Oak, .back = sRhPg8_Back, .backPal = sRhPg8_BackPal },
    { .normal = sRhPg9_PicNormal, .surf = sRhPg9_PicSurf, .bike = sRhPg9_PicBike, .fish = sRhPg9_PicFish, .item = sRhPg9_PicItem, .itemBike = sRhPg9_PicItemBike, .front = sRhPg9_Front, .frontPal = sRhPg9_FrontPal, .oak = sRhPg9_Oak, .back = sRhPg9_Back, .backPal = sRhPg9_BackPal },
    { .normal = sRhPg10_PicNormal, .surf = sRhPg10_PicSurf, .bike = sRhPg10_PicBike, .fish = sRhPg10_PicFish, .item = sRhPg10_PicItem, .itemBike = sRhPg10_PicItemBike, .front = sRhPg10_Front, .frontPal = sRhPg10_FrontPal, .oak = sRhPg10_Oak, .back = sRhPg10_Back, .backPal = sRhPg10_BackPal },
    { .normal = sRhPg11_PicNormal, .surf = sRhPg11_PicSurf, .bike = sRhPg11_PicBike, .fish = sRhPg11_PicFish, .item = sRhPg11_PicItem, .itemBike = sRhPg11_PicItemBike, .front = sRhPg11_Front, .frontPal = sRhPg11_FrontPal, .oak = sRhPg11_Oak, .back = sRhPg11_Back, .backPal = sRhPg11_BackPal },
    { .normal = sRhPg12_PicNormal, .surf = sRhPg12_PicSurf, .bike = sRhPg12_PicBike, .fish = sRhPg12_PicFish, .item = sRhPg12_PicItem, .itemBike = sRhPg12_PicItemBike, .front = sRhPg12_Front, .frontPal = sRhPg12_FrontPal, .oak = sRhPg12_Oak, .back = sRhPg12_Back, .backPal = sRhPg12_BackPal },
};
const u8 *const gRhPlayerGraphicsNames[] = {
    COMPOUND_STRING("Default"),
    COMPOUND_STRING("Ethan"),
    COMPOUND_STRING("Kris"),
    COMPOUND_STRING("Red (FR/LG)"),
    COMPOUND_STRING("Leaf"),
    COMPOUND_STRING("Brendan (E)"),
    COMPOUND_STRING("May (E)"),
    COMPOUND_STRING("Brendan (R/S)"),
    COMPOUND_STRING("May (R/S)"),
    COMPOUND_STRING("Wally"),
    COMPOUND_STRING("Prof. Birch"),
    COMPOUND_STRING("Cynthia"),
    COMPOUND_STRING("Ghost (Snakewood)"),
    COMPOUND_STRING("Wraith (Snakewood)"),
};
const u8 gRhPlayerGraphicsCount = ARRAY_COUNT(gRhPlayerGraphicsNames);
