// AUTO-GENERATED by tools/rh/gen_shops.py - do not edit by hand
struct RhMartEntry { u8 minBadges; u16 item; };

static const struct RhMartEntry sRhProgressive[] = {
    {0, ITEM_HEAL_BALL},
    {0, ITEM_EXP_CANDY_XS},
    {0, ITEM_LURE},
    {1, ITEM_NEST_BALL},
    {1, ITEM_NET_BALL},
    {1, ITEM_EXP_CANDY_S},
    {1, ITEM_HEALTH_FEATHER},
    {1, ITEM_MUSCLE_FEATHER},
    {1, ITEM_RESIST_FEATHER},
    {1, ITEM_GENIUS_FEATHER},
    {1, ITEM_CLEVER_FEATHER},
    {1, ITEM_SWIFT_FEATHER},
    {2, ITEM_REPEAT_BALL},
    {2, ITEM_TIMER_BALL},
    {2, ITEM_DIVE_BALL},
    {2, ITEM_SUPER_LURE},
    {2, ITEM_HEALTH_MOCHI},
    {2, ITEM_MUSCLE_MOCHI},
    {2, ITEM_RESIST_MOCHI},
    {2, ITEM_GENIUS_MOCHI},
    {2, ITEM_CLEVER_MOCHI},
    {2, ITEM_SWIFT_MOCHI},
    {2, ITEM_FRESH_START_MOCHI},
    {3, ITEM_QUICK_BALL},
    {3, ITEM_DUSK_BALL},
    {3, ITEM_LUXURY_BALL},
    {3, ITEM_EXP_CANDY_M},
    {4, ITEM_LEVEL_BALL},
    {4, ITEM_LURE_BALL},
    {4, ITEM_MOON_BALL},
    {4, ITEM_FRIEND_BALL},
    {4, ITEM_LOVE_BALL},
    {4, ITEM_FAST_BALL},
    {4, ITEM_HEAVY_BALL},
    {4, ITEM_MAX_LURE},
    {5, ITEM_EXP_CANDY_L},
    {5, ITEM_MAX_ETHER},
    {5, ITEM_ELIXIR},
    {8, ITEM_EXP_CANDY_XL},
    {8, ITEM_MAX_ELIXIR},
};

static const struct RhMartEntry sRhThemed_VIRIDIAN[] = {
    {0, ITEM_EVERSTONE},
    {7, ITEM_SOFT_SAND},
    {7, ITEM_GROUND_GEM},
    {7, ITEM_IRON_BALL},
    {7, ITEM_TERRAIN_EXTENDER},
    {7, ITEM_BINDING_BAND},
    {7, ITEM_GRIP_CLAW},
    {0, ITEM_NONE},
};
static const struct RhMartEntry sRhThemed_PEWTER[] = {
    {0, ITEM_HARD_STONE},
    {0, ITEM_ROCK_GEM},
    {0, ITEM_ROCK_INCENSE},
    {0, ITEM_SMOOTH_ROCK},
    {0, ITEM_PROTECTIVE_PADS},
    {0, ITEM_FLOAT_STONE},
    {0, ITEM_SILK_SCARF},
    {0, ITEM_NORMAL_GEM},
    {0, ITEM_NONE},
};
static const struct RhMartEntry sRhThemed_CERULEAN[] = {
    {0, ITEM_MYSTIC_WATER},
    {0, ITEM_WATER_GEM},
    {0, ITEM_SEA_INCENSE},
    {0, ITEM_WAVE_INCENSE},
    {0, ITEM_DAMP_ROCK},
    {0, ITEM_ABSORB_BULB},
    {0, ITEM_SHELL_BELL},
    {0, ITEM_BIG_ROOT},
    {0, ITEM_NONE},
};
static const struct RhMartEntry sRhThemed_VERMILION[] = {
    {0, ITEM_MAGNET},
    {0, ITEM_ELECTRIC_GEM},
    {0, ITEM_CELL_BATTERY},
    {0, ITEM_ELECTRIC_SEED},
    {0, ITEM_AIR_BALLOON},
    {0, ITEM_SHARP_BEAK},
    {0, ITEM_FLYING_GEM},
    {0, ITEM_METRONOME},
    {0, ITEM_ZOOM_LENS},
    {0, ITEM_NONE},
};
static const struct RhMartEntry sRhThemed_LAVENDER[] = {
    {0, ITEM_SPELL_TAG},
    {0, ITEM_GHOST_GEM},
    {0, ITEM_CLEANSE_TAG},
    {0, ITEM_SMOKE_BALL},
    {0, ITEM_BLACK_GLASSES},
    {0, ITEM_DARK_GEM},
    {0, ITEM_SOOTHE_BELL},
    {0, ITEM_NONE},
};
static const struct RhMartEntry sRhThemed_CELADON[] = {
    {0, ITEM_MIRACLE_SEED},
    {0, ITEM_GRASS_GEM},
    {0, ITEM_ROSE_INCENSE},
    {0, ITEM_GRASSY_SEED},
    {0, ITEM_LUMINOUS_MOSS},
    {0, ITEM_MUSCLE_BAND},
    {0, ITEM_WISE_GLASSES},
    {0, ITEM_NONE},
};
static const struct RhMartEntry sRhThemed_FUCHSIA[] = {
    {0, ITEM_POISON_BARB},
    {0, ITEM_POISON_GEM},
    {0, ITEM_BLACK_SLUDGE},
    {0, ITEM_TOXIC_ORB},
    {0, ITEM_SILVER_POWDER},
    {0, ITEM_BUG_GEM},
    {0, ITEM_QUICK_CLAW},
    {0, ITEM_WIDE_LENS},
    {0, ITEM_STICKY_BARB},
    {0, ITEM_NONE},
};
static const struct RhMartEntry sRhThemed_SAFFRON[] = {
    {0, ITEM_TWISTED_SPOON},
    {0, ITEM_PSYCHIC_GEM},
    {0, ITEM_ODD_INCENSE},
    {0, ITEM_PSYCHIC_SEED},
    {0, ITEM_LIGHT_CLAY},
    {0, ITEM_SCOPE_LENS},
    {0, ITEM_RED_CARD},
    {0, ITEM_EJECT_BUTTON},
    {0, ITEM_ROOM_SERVICE},
    {0, ITEM_BLACK_BELT},
    {0, ITEM_FIGHTING_GEM},
    {0, ITEM_PUNCHING_GLOVE},
    {0, ITEM_NONE},
};
static const struct RhMartEntry sRhThemed_CINNABAR[] = {
    {0, ITEM_CHARCOAL},
    {0, ITEM_FIRE_GEM},
    {0, ITEM_HEAT_ROCK},
    {0, ITEM_FLAME_ORB},
    {0, ITEM_UTILITY_UMBRELLA},
    {0, ITEM_HEAVY_DUTY_BOOTS},
    {0, ITEM_SAFETY_GOGGLES},
    {0, ITEM_THROAT_SPRAY},
    {0, ITEM_NONE},
};
static const struct RhMartEntry sRhThemed_INDIGO[] = {
    {0, ITEM_DRAGON_FANG},
    {0, ITEM_DRAGON_GEM},
    {0, ITEM_NEVER_MELT_ICE},
    {0, ITEM_ICE_GEM},
    {0, ITEM_BLUNDER_POLICY},
    {0, ITEM_ADRENALINE_ORB},
    {0, ITEM_EJECT_PACK},
    {0, ITEM_ABILITY_SHIELD},
    {0, ITEM_NONE},
};
static const struct RhMartEntry sRhThemed_THREE_ISLAND[] = {
    {0, ITEM_METAL_COAT},
    {0, ITEM_STEEL_GEM},
    {0, ITEM_SHED_SHELL},
    {0, ITEM_RING_TARGET},
    {0, ITEM_LAGGING_TAIL},
    {0, ITEM_BRIGHT_POWDER},
    {0, ITEM_FOCUS_BAND},
    {0, ITEM_NONE},
};
static const struct RhMartEntry sRhThemed_FOUR_ISLAND[] = {
    {0, ITEM_ICY_ROCK},
    {0, ITEM_SNOWBALL},
    {0, ITEM_FULL_INCENSE},
    {0, ITEM_LAX_INCENSE},
    {0, ITEM_DESTINY_KNOT},
    {0, ITEM_NONE},
};
static const struct RhMartEntry sRhThemed_SIX_ISLAND[] = {
    {0, ITEM_FAIRY_GEM},
    {0, ITEM_MISTY_SEED},
    {0, ITEM_FAIRY_FEATHER},
    {0, ITEM_PURE_INCENSE},
    {0, ITEM_LUCK_INCENSE},
    {0, ITEM_KINGS_ROCK},
    {0, ITEM_NONE},
};
static const struct RhMartEntry sRhThemed_SEVEN_ISLAND[] = {
    {0, ITEM_MACHO_BRACE},
    {0, ITEM_POWER_WEIGHT},
    {0, ITEM_POWER_BRACER},
    {0, ITEM_POWER_BELT},
    {0, ITEM_POWER_LENS},
    {0, ITEM_POWER_BAND},
    {0, ITEM_POWER_ANKLET},
    {0, ITEM_NONE},
};
static const struct RhMartEntry sRhThemed_TRAINER_TOWER[] = {
    {0, ITEM_NONE},
};
extern const u16 ViridianCity_Mart_Items[];
extern const u16 PewterCity_Mart_Items[];
extern const u16 CeruleanCity_Mart_Items[];
extern const u16 VermilionCity_Mart_Items[];
extern const u16 LavenderTown_Mart_Items[];
extern const u16 CeladonCity_DepartmentStore_2F_Items[];
extern const u16 FuchsiaCity_Mart_Items[];
extern const u16 SaffronCity_Mart_Items[];
extern const u16 CinnabarIsland_Mart_Items[];
extern const u16 IndigoPlateau_PokemonCenter_1F_Items[];
extern const u16 ThreeIsland_Mart_Items[];
extern const u16 FourIsland_Mart_Items[];
extern const u16 SixIsland_Mart_Items[];
extern const u16 SevenIsland_Mart_Items[];
extern const u16 TrainerTower_Lobby_Mart_Items[];

static const struct { const u16 *base; const struct RhMartEntry *themed; } sRhMarts[RH_MART_COUNT] = {
    [RH_MART_VIRIDIAN] = {ViridianCity_Mart_Items, sRhThemed_VIRIDIAN},
    [RH_MART_PEWTER] = {PewterCity_Mart_Items, sRhThemed_PEWTER},
    [RH_MART_CERULEAN] = {CeruleanCity_Mart_Items, sRhThemed_CERULEAN},
    [RH_MART_VERMILION] = {VermilionCity_Mart_Items, sRhThemed_VERMILION},
    [RH_MART_LAVENDER] = {LavenderTown_Mart_Items, sRhThemed_LAVENDER},
    [RH_MART_CELADON] = {CeladonCity_DepartmentStore_2F_Items, sRhThemed_CELADON},
    [RH_MART_FUCHSIA] = {FuchsiaCity_Mart_Items, sRhThemed_FUCHSIA},
    [RH_MART_SAFFRON] = {SaffronCity_Mart_Items, sRhThemed_SAFFRON},
    [RH_MART_CINNABAR] = {CinnabarIsland_Mart_Items, sRhThemed_CINNABAR},
    [RH_MART_INDIGO] = {IndigoPlateau_PokemonCenter_1F_Items, sRhThemed_INDIGO},
    [RH_MART_THREE_ISLAND] = {ThreeIsland_Mart_Items, sRhThemed_THREE_ISLAND},
    [RH_MART_FOUR_ISLAND] = {FourIsland_Mart_Items, sRhThemed_FOUR_ISLAND},
    [RH_MART_SIX_ISLAND] = {SixIsland_Mart_Items, sRhThemed_SIX_ISLAND},
    [RH_MART_SEVEN_ISLAND] = {SevenIsland_Mart_Items, sRhThemed_SEVEN_ISLAND},
    [RH_MART_TRAINER_TOWER] = {TrainerTower_Lobby_Mart_Items, sRhThemed_TRAINER_TOWER},
};
